### ISSUE TITLE
CURL Error #:Could not resolve host: api.comprobanteselectronicos.go.cr

### ISSUE THREAD

**Issue by SocaaSoftware** [CRLibre/API_Hacienda#111]
**Describa el problema** *(bug)*
$.post("https://api-demo.crlibre.org/api.php", {r: (rhacienda), w: (whacienda), url: (urlhacienda), grant_type: (grant_typehacienda), client_id: (client_idhacienda), username: (usernamehacienda), password: (passwordhacienda)},function(data)
				{});

Esta llamada da una respuesta del Token, sin embargo si lo intento con el api.php en mi servidor indica que no pudo resolver el host???

**Pasos para reproducir**
Se copiaron los archivos correctamente, se modifico el archivo de configuracion, el archivo Api.php funciona correctamente, pero la respuesta esta erronea.

**Versión API:** *Recien descargada la libreria*

**Sistema operativo:** *Ubuntu*

**PHP versión:** *7.2*

**MySQL versión:** *ND*

**Respuesta nula del Curl**

**$.post("https://api-demo.crlibre.org/api.php", {r: (rhacienda), w: (whacienda), url: (urlhacienda), grant_type: (grant_typehacienda), client_id: (client_idhacienda), username: (usernamehacienda), password: (passwordhacienda)},function(data)
				{});

Esta llamada da una respuesta del Token, sin embargo si lo intento con el api.php en mi servidor indica que no pudo resolver el host???

**

**Comment by JeanCarlosChavarriaHughes** [comment]
Que le devuelve ```nslookup api.comprobanteselectronicos.go.cr``` ?

**Comment by SocaaSoftware** [comment]
5 minutes | A | 104.20.5.119
5 minutes | A | 104.20.6.119
5 minutes | AAAA | 2606:4700:10::6814:577
5 minutes | AAAA | 2606:4700:10::6814:677

**Comment by eliastorres** [comment]
Este tipo de problema es más de infraestructura "Could not resolve host" es un problema del sistema de resolución de nombres del equipo donde se corre el sisteama, esto involucra DNS.
