### ISSUE TITLE
Valor de TotalExonerado es igual al de $totalExento

### ISSUE THREAD

**Issue by bryannsi** [CRLibre/API_Hacienda#114]
### Descripción del problema:

Al generar un documento _xml_, en la sección **ResumenFactura**, la etiqueta **TotalExonerado** toma como valor la variable que contiene el total exento **$totalExento**.

Esto provoca que si se envían los parámetros:
```
...
total_serv_exonerados: 0.00000,
total_merc_exonerada: 0.00000,
total_exonerado: 0.00000,
total_exento: 100.00000,
...
 ```

Una vez decodificado el xmlBase64, tendrá la siguiente estructura:
```
<ResumenFactura>
    ...
    <TotalServExonerado>0.00000</TotalServExonerado>
    <TotalMercExonerada>0.00000</TotalMercExonerada>
    <TotalExonerado>100.00000</TotalExonerado>
    <TotalExento>100.00000</TotalExento>
    ...
</ResumenFactura>
``` 

### Comportamiento esperado.
La  etiqueta ```<TotalExonerado>100.00000</TotalExonerado>``` debe contener el valor de 0.

### Solución propuesta.
Modificar la variable **$totalExento** que contienen las etiquetas
```
<TotalExonerado>' . $totalExento . '</TotalExonerado>';
```
a **$totalExonerado**
```
<TotalExonerado>' . $totalExonerado . '</TotalExonerado>';
```

Esto se encuentra en las líneas: [L493](https://github.com/CRLibre/API_Hacienda/blob/master/api/contrib/genXML/genXML.php#L493), [L1048](https://github.com/CRLibre/API_Hacienda/blob/master/api/contrib/genXML/genXML.php#L1048), [L1594](https://github.com/CRLibre/API_Hacienda/blob/master/api/contrib/genXML/genXML.php#L1594) y [L2131](https://github.com/CRLibre/API_Hacienda/blob/master/api/contrib/genXML/genXML.php#L2131)

**Comment by JeanCarlosChavarriaHughes** [comment]
Fixed
