### ISSUE TITLE
Excelente Aplicavión Me pregunto como puedo hacer para adaptarla a la DIAN Colombia, tienes algo paracedido, gracias

### ISSUE THREAD

**Issue by henrypandales** [CRLibre/API_Hacienda#116]
Tengo una aplicacion similar en php pero deseo aplicarle facturación electronica para Colombia, la verad es que esta se ve entendible y muy sencilla 

Habrá alguna forma o tienes algo parecido??

gracias

Favor me escribes al whatsapp +57 314 775 4208 
Henry Pandales

**Comment by eliastorres** [comment]
Duplicate #118
