### ISSUE TITLE
Excelente trabajo muy bien concebido pero deseo migralo para DIAN Colombia cómo puedo hacerlo??

### ISSUE THREAD

**Issue by henrypandales** [CRLibre/API_Hacienda#118]
**Describa el problema** *(bug)*
Una descripción clara de cual es el problema.

**Pasos para reproducir**
Pasos para reproducir

**Versión API:** *Lea como obtener la versión del API https://github.com/CRLibre/API_Hacienda/blob/master/VERSION.md*

**Sistema operativo:** *Cambiar por el S.O. (Windows, Linux, etc)*

**PHP versión:** *Cambiar por versión PHP.*

**MySQL versión:** *Cambiar por versión MySQL.*

**Comportamiento esperado**
Lo que debería pasar.

**Capturas de pantalla o registro de bitácora**
Si aplica, por favor adjuntar capturas, registros de logs con mensajes de error o XML (lo puedes subir a https://gist.github.com y nos compartes el enlace).

**Contexto adicional**
Cualquier otro contexto acá.

**Comment by henrypandales** [comment]
Excelente trabajo muy bien concebido pero deseo migralo para DIAN Colombia cómo puedo hacerlo??

**Comment by JeanCarlosChavarriaHughes** [comment]
@henrypandales aún sigues interesado en la implementación de un proyecto similar para DIAN Colombia?
