### ISSUE TITLE
Error -1 cuando el módulo no es identificado.

### ISSUE THREAD

**Issue by jdpc91** [CRLibre/API_Hacienda#14]
Cuando se realiza una petición con un parámetro w desconocido devuelve -1 el cual es un error muy genérico. Hay que poner un código de error o un mensaje que puede decir algo como "módulo desconocido"

**Comment by alejosv** [comment]
@jdpc91 en cuál módulo se genera esto?

**Comment by walner1borbon** [comment]
Se agrego la funcionalidad que identifica si el modulo no existe y si la funcion no existe
![image](https://user-images.githubusercontent.com/20653503/40755204-96c145c0-643a-11e8-8897-bfc479f13836.png)

**Comment by eliastorres** [comment]
Implementado en este _commit_: a356bad4064629f5de3371c8786709303fef54a4
