### ISSUE TITLE
[Modificar] [Mecanismo de Seguridad] [Cambio del nombre del nodo]

### ISSUE THREAD

**Issue by JeanCarlosChavarriaHughes** [CRLibre/API_Hacienda#142]
Referencia:

`107.Se ajusta el nombre del nodo de firma actual pasando de llamarse “Nodo para las firmas XAdES” a “Nodo par la firmas XadES del emisor del comprobante”
`

**Comment by fdelapena** [comment]
Esto probablemente va a cambiar notablemente (incluyendo lo mencionado en #142 y #143), ya que el diseño de firmas no era compatible con XMLDsig.

Propuse una mejora al borrador en el que las firmas digitales se conservarían tal cual. La firma principal como hasta ahora (Emisor) no requeriría cambios en los sistemas de facturación, mientras que los endosantes, endosatarios y receptor serían contrafirmas XAdES. Para distinguir quién es quién se utilizaría un atributo firmado SignerRole de XAdES.

Este es un avance de la enmienda tras la propuesta:

![enmienda-borrador](https://user-images.githubusercontent.com/174885/174203530-e608a7d6-c983-4153-a53d-b0681bfa5c3a.jpg)

Más información:
- Contrafirmas: https://www.w3.org/TR/XAdES/#Syntax_for_XAdES_The_CounterSignature_element
- Rol de firmante: https://www.w3.org/TR/XAdES/#Syntax_for_XAdES_The_SignerRole_element

Si finalmente la 4.4 aplica estos cambios subiría una muestra de un xml contrafirmado con esta estructura.
