### ISSUE TITLE
[Agregar] [Nuevo apartado] [Endoso de Comprobante]

### ISSUE THREAD

**Issue by JeanCarlosChavarriaHughes** [CRLibre/API_Hacienda#144]
Referencia:

```
109.Se incluye el apartado de “Endoso del Comprobante”
110.Se incluye un nuevo nodo para la firma denominado “Nodo para las firmas XadES: Endoso / endosante”
111.Se incluye un nuevo nodo para la firma denominado “Nodo para las firmas XadES: Endoso /endosatario”
112.Se incluye en la nota 11, el código 4, Alerta Endoso: Mensaje Exlusivo de la plataforma de Validación del Ministerio de Hacienda. En caso de recibirse un
comprobante electrónico endosado que presente vulneraciones o inconsistencias en el schema del archivo xml y que no permita su almacenamiento, se generará
el código de mensaje 4, el cual no representa un rechazo, pero será notificado a la plataforma de facturación del endosatario que haya enviado el comprobante
endosado.
```

Se pueden realizar como máximo hasta 3 repeticiones de endoso
Nota importante: En caso de Requerirse en el comprobante electrónico el apartado de endoso, será responsabilidad del endosante emisor, incorporar esta opción en la estructura antes de generar
y firmar el comprobante por primera vez, para que tanto el endosante como el endosatario posteriormente a la emisión del comprobante electrónico únicamente incorporen la firma, con el fin de no
alterar el contenido del comprobante electrónico, dicha firma debe de estar al amparo bajo la Ley 8454 denominada “Ley de certificados, firmas digitales y documentos electrónicos, emitidas por las
entidades bancarias.

**Comment by fdelapena** [comment]
Esto probablemente va a cambiar notablemente (incluyendo lo mencionado en #142 y #143), ya que el diseño de firmas no era compatible con XMLDsig.

Propuse una mejora al borrador en el que las firmas digitales se conservarían tal cual. La firma principal como hasta ahora (Emisor) no requeriría cambios en los sistemas de facturación, mientras que los endosantes, endosatarios y receptor serían contrafirmas XAdES. Para distinguir quién es quién se utilizaría un atributo firmado SignerRole de XAdES.

Este es un avance de la enmienda tras la propuesta:

![enmienda-borrador](https://user-images.githubusercontent.com/174885/174203530-e608a7d6-c983-4153-a53d-b0681bfa5c3a.jpg)

Más información:
- Contrafirmas: https://www.w3.org/TR/XAdES/#Syntax_for_XAdES_The_CounterSignature_element
- Rol de firmante: https://www.w3.org/TR/XAdES/#Syntax_for_XAdES_The_SignerRole_element

Si finalmente la 4.4 aplica estos cambios subiría una muestra de un xml contrafirmado con esta estructura.

**Comment by JeanCarlosChavarriaHughes** [comment]
Este apartado no fue incluido en la nueva normativa oficial v4.4
Esta tarea se puede cerrar ya que no es necesaria.

Los cambios en el apartado de Mecanismo de seguridad se deben centralizar y realizar bajo el issue: #143
