### ISSUE TITLE
Error en la documentación: clave vs getClave

### ISSUE THREAD

**Issue by jdpc91** [CRLibre/API_Hacienda#15]
En https://github.com/CRLibre/API_Hacienda/wiki/Creaci%C3%B3n-de-Clave-para-los-XML-de-Factura-Electr%C3%B3nica para obtener la clave el parámetro r debe ser "clave" y no "getClave"

**Comment by walner1borbon** [comment]
Ya lo corregi y deje el parametro como esta en el wiki w=clave r=clave
Gracias por la observacion
