### ISSUE TITLE
Respuesta de Hacienda. 

### ISSUE THREAD

**Issue by IngJaneB** [CRLibre/API_Hacienda#160]
**Describa el problema** *(bug)*
Hola, un gusto en saludarles. Al momento de enviar la Factura electronica, hacienda me indica el siguiente mensaje: 

resp |  
Status | 0
to | "api_stag"
text | "No URL set!"

Consulte con ellos y me indicaron que es que tengo mala la url y me recomendaron https://api-sandbox.comprobanteselectronicos.go.cr/recepcion/v1/recepcion/ cosa que revice y en la API esta la misma. Indicandole a Hacienda me indican que por el XML pero estoy enviando todo los campos o eso creo:

'w'=> 'genXML',
                "r"=> "gen_xml_fe",
                "clave"=>$clave_fact,
                "codigo_actividad"=>"221901",
                "consecutivo"=>$consecutivo_fact,
                "fecha_emision"=>date("Y-m-d\TH:i:sP"),
                "emisor_nombre"=>"Diego Valverde",
                "emisor_tipo_identif"=>"01",
                "emisor_num_identif"=>"11234569",
                "emisor_nombre_comercial"=>"xxxxx",
                "emisor_provincia"=>"06",
                "emisor_canton"=>"02",
                "emisor_distrito"=>"03",
                "emisor_barrio"=>"01",
                "emisor_otras_senas"=>"Frente a la escuela",
                "emisor_cod_pais_tel"=>"506",
                "emisor_tel"=>"64206205",
                "emisor_cod_pais_fax"=>"506",
                "emisor_fax"=>"00000000",
                "emisor_email"=>"tsu.jackelineestaba@gmail.com",
                "receptor_nombre"=>"Jackeline Estaba",
                "receptor_tipo_identif"=>"01",
                "receptor_num_identif"=>"11234569",
                "receptor_nombre_comercial"=>"xxxxx",
                "receptor_provincia"=>"06",
                "receptor_canton"=>"02",
                "receptor_distrito"=>"03",
                "receptor_barrio"=>"01",
                "receptor_otras_senas"=>"Frente a la Casa",
                "receptor_otras_senas_extranjero"=>"",
                "receptor_cod_pais_tel"=>"506",
                "receptor_tel"=>"84922891",
                "receptor_cod_pais_fax"=>"506",
                "receptor_fax"=>"00000000",
                "receptor_email"=>"tec.jackelineestaba@gmail.com",
                "condicion_venta"=>"01",
                "plazo_credito"=>"0",
                "medio_pago"=>"",
                "medios_pago"=>"01",
                "cod_moneda"=>"CRC",
                "tipo_cambio"=>"564.48",
                "total_serv_gravados"=>"0",
                "total_serv_exentos"=>"200000",
                "total_serv_exonerados"=>"0",
                "total_merc_gravada"=>"0",
                "total_merc_exenta"=>"0",
                "total_merc_exonerada"=>"200000",
                "total_gravados"=>"200000",
                "total_exento"=>"200000",
                "total_exonerado"=>"0",
                "total_ventas"=>"200000",
                "total_descuento"=>"0",
                "total_ventas_neta"=>"200000",
                "total_impuesto"=>"0",
                //"totalIvaDevuelto"=>"0",
                //"totalOtrosCargos"=>"0",
                "total_comprobante"=>"200000",
                "otros"=>"Muchas Gracias",
                "otrosType"=>'',
                "detalles"=>'{"1" : {"cantidad" : "1","unidadMedida" : "Sp","detalle" : "Impresora","precioUnitario" : "10000","montoTotal" : "10000","subtotal" : "9900","montoTotalLinea" : "9900","montoDescuento" : "100","naturalezaDescuento" : "Pronto pago"}, "2" : {"cantidad" : "1","unidadMedida" : "Unid","detalle" : "producto","precioUnitario" : "10000","montoTotal" : "10000","subtotal" : "10000","montoTotalLinea" : "11170","impuesto" : {"1" : {"codigo" : "01","tarifa" : "11.7","monto" : "1170"}}}}

Si me falta alguno mencionarlo. Lamentablemente no soy muy conocedora de los campos obligatorios del XML. Todas las variables estan definidas y el XML cuando se genera se firma en otra solicitud como indica la guia del WIKI. Agradezco de antemano su colaboración y disculpen lo largo y el poco conocimiento. Gracias. 

**Pasos para reproducir**
Pasos para reproducir

**Versión API:** *Lea como obtener la versión del API https://github.com/CRLibre/API_Hacienda/blob/master/VERSION.md*

**Sistema operativo:** *Cambiar por el S.O. (Windows, Linux, etc)*

**PHP versión:** *Cambiar por versión PHP.*

**MySQL versión:** *Cambiar por versión MySQL.*

**Comportamiento esperado**
Lo que debería pasar.

**Capturas de pantalla o registro de bitácora**
Si aplica, por favor adjuntar capturas, registros de logs con mensajes de error o XML (lo puedes subir a https://gist.github.com y nos compartes el enlace).

**Contexto adicional**
Cualquier otro contexto acá.

**Comment by JeanCarlosChavarriaHughes** [comment]
Hola @IngJaneB 

_Al momento de enviar la Factura electronica, hacienda me indica el siguiente mensaje_
El método genXML es para generar el XML. Este método no lo envía a Hacienda.


El método para enviarlo a hacienda es send. 
Si el XML firmado se envía a hacienda, y hacienda lo rechaza, entonces en el rechazo indica el motivo de por qué se rechazó.

_Lamentablemente no soy muy conocedora de los campos obligatorios del XML._
Puedes revisar la información sobre los campos obligatorios de los XML en el link de Hacienda: https://atv.hacienda.go.cr/ATV/ComprobanteElectronico/frmAnexosyEstructuras.aspx# 

Puedes hacer una prueba desde postman, usando valores en lugar de variables. Esto le puede servir para entender los datos que se envían y encontrar posibles errores.
"consecutivo"=>$consecutivo_fact,
"fecha_emision"=>date("Y-m-d\TH:i:sP"),

Otro que veo es que
medios pago espera un arreglo. Medio pago espera un valor. Puedes revisar el gen_xml.php
ejemplo: 
medios_pago= [{ "codigo": "01"}]

**Comment by IngJaneB** [comment]
Si Correcto, luego que envio el XML con la Firma en Base 64 (por el metodo SEND) es alli donde me da respuesta No URL set.  Le he colocado los datos obligatorios y cambie las variables por los texto pero aun me indica como si la URL de envio no fuera la correcta. Tines un XML de prueba que halla sido aceptado para enviarlo como prueba? Use el que tiene en el Wiki pero aun asi me indica el mismo error :(

**Comment by JeanCarlosChavarriaHughes** [comment]
Hola @IngJaneB 
Creo que este XML le puede servir:

[comprobanteXML1](https://gist.githubusercontent.com/JeanCarlosChavarriaHughes/a27d356ccb4892bb11a4896370030624/raw/a96fc5a895730032f4cba930c227412c7aaaa7ff/gistfile1.txt)

**Comment by IngJaneB** [comment]
Hola! Creo que puedo saber por donde va el error. Hice una prueba mandando directo a Hacienda por el Postman y el XML fue aceptado, pero no me devolvio nada, luego me di cuenta de que habia otro parametro que no coloque que es el callbackUrl que es donde deberia llegarme la Respuesta de Hacienda Correcto?

                 w'=> 'send',
                "r"=> "json",
                "token"=>$token_access,
                "clave"=>$clave_fact,
                "fecha"=>$fecha_xml,
                "emi_tipoIdentificacion"=>"02",
                "emi_numeroIdentificacion"=>"3004864485",
                "recp_tipoIdentificacion"=>"01",
                "recp_numeroIdentificacion"=>"701160197",
                "comprobanteXml"=>$xml_firmado,
                "callbackUrl"=>"", //Lo Acabo de agregar. 
                "client_id"=>"api_stag"

Lo que no entiendo muy bien que debo colocar en la misma. En caso que quiera que me retorme la respuesta . Probe enviando vacio pero me envia la misma respuesta. Como indique arriba ya queda descartado el XML y los parametros. Gracias de antemano y disculpe tantas molestias

**Comment by JeanCarlosChavarriaHughes** [comment]
@IngJaneB  el problema que indicas en realidad no es con la API, sino con el flujo de como funciona el sistema de Hacienda.
Ellos tienen otro endpoint para consultar el status.
Lo usual es 

1. hacer login
2. crear el token
3. crear el XML
4. firmar el XML
5. enviar el XML
6. consultar a hacienda por la clave específica.

Al enviar "send" hacienda responde con un Status 202. Pero luego hay que consultar el estado en otro llamado distinto.
El callbackUrl es opcional, por si tienes un servidor distinto escuchando ese 202, pero eso es opcional. No es parte del flujo convencional.

Algo como este flujo:
https://github.com/CRLibre/API_Hacienda/wiki/Diagrama-de-flujo-Factura-Electr%C3%B3nica-Costa-Rica 
Tal vez la confusión es que hace falta la etapa de consulta en ese diagrama.

**Comment by JeanCarlosChavarriaHughes** [comment]
@IngJaneB pudo resolver el issue? Para cerrar el reporte.

**Comment by JeanCarlosChavarriaHughes** [comment]
Unable to reproduce.
