### ISSUE TITLE
Error al subir certificados cuando se ejecuta con Docker

### ISSUE THREAD

**Issue by achaconm2001** [CRLibre/API_Hacienda#167]
**Describa el problema** *(bug)*
Estoy siguiendo esta guía para subir un certificado https://github.com/CRLibre/API_Hacienda/wiki/Upload-del-certificado-o-llave-criptogr%C3%A1fica
En lugar de recibir el JSON esperado, el API retorna un { resp: "-402" }
Investigando un poco el API, creo que el error viene de aquí https://github.com/CRLibre/API_Hacienda/blob/3f0855f9ef672c0391f55d39c18f73e333877a86/api/modules/files/module.php#L255 y se reproduce por un error en la función move_uploaded_file de php.
Al hostear el API por medio de Docker, creo que puede que haya algún problema con los permisos para escribir al directorio 

**Pasos para reproducir**
1. Tener una VM con Ubuntu 24.04 (LTS) x64
2. Clonar el repositorio
3. Ejecutar: docker-compose -f "docker-compose.yml" up -d --build
4. Seguir los pasos para crearse una cuenta: https://github.com/CRLibre/API_Hacienda/wiki/Creaci%C3%B3n-de-Usuario
5. Tratar de subir el certificado: https://github.com/CRLibre/API_Hacienda/wiki/Upload-del-certificado-o-llave-criptogr%C3%A1fica

**Versión API:** 
git log --pretty="%h" -n1 = 3f0855f

**Sistema operativo:** 
Ubuntu 24.04 (LTS) x64

**PHP versión:** 
php:7.4.9-apache (docker compose)

**MySQL versión:**
mariadb:10.11.4 (docker compose)

**Comportamiento esperado**
![image](https://github.com/CRLibre/API_Hacienda/assets/28637127/15c25bc7-a98a-430f-8d38-e3969f77c29d)

**Capturas de pantalla o registro de bitácora**
![Captura de pantalla 2024-06-30 030746](https://github.com/CRLibre/API_Hacienda/assets/28637127/39ac1786-199a-492c-b462-8f6673f0fce6)

**Contexto adicional**
Gracias :D

**Comment by JeanCarlosChavarriaHughes** [comment]
Hola Andrés @achaconm2001

> En lugar de recibir el JSON esperado, el API retorna un { resp: "-402" }

Podrías confirmar que los permisos de escritura de directorio api y files estén habilitados.
Adentro de la carpeta "api" hay una carpeta que se llama "files"
Dale los permisos de escritura y a las subcarpetas.

> ¿Es posible o recomendado utiliza el API https://api-demo.crlibre.org/api.php en lugar de hostear el servidor uno mismo?
No creo que sea recomendado, pues actualmente el servicio que mencionas solamente es un demo, no está pensado para ser usado en producción, no está activamente monitoreado, ni tiene mantenimiento. Lo correcto es que cada colaborador tenga su propio servicio en su propio servidor.

**Comment by JeanCarlosChavarriaHughes** [comment]
Hola, @achaconm2001 
Perfecto que ya pudo resolver el issue. 

Podrías por favor crear el PR con el fix que mencionas, y me asignas para revisarlo y agregarlo al branch de develop `dev`.
Saludos.
