### ISSUE TITLE
Ruta de envio a Hacienda

### ISSUE THREAD

**Issue by agcgithub** [CRLibre/API_Hacienda#21]
Tengo dudas con respecto al URL de SANDBOX necesario para enviar el POST para la firma.    Cuando genere la clave en ATV me da una ruta, pero aparentemente esa me da un 404 .  Sitio no existe,

Cual es la ruta correcta para el envìo de documento y luego la ruta para consultar dicho envìo.

Gracias

**Comment by walner1borbon** [comment]
En esos 2 modulos puedes ver esas rutas
Envio a hacienda produccion y sandbox
if ($apiTo == 'api-stag') {
    $url = "https://api.comprobanteselectronicos.go.cr/recepcion-sandbox/v1/recepcion/";
} else if ($apiTo == 'api-prod') {
    $url = "https://api.comprobanteselectronicos.go.cr/recepcion/v1/recepcion/";
}
https://github.com/CRLibre/API_Hacienda/blob/master/api/contrib/send/send.php

Consultar a Hacienda
https://github.com/CRLibre/API_Hacienda/blob/master/api/contrib/consultar/consultar.php
    if (params_get("client_id") == 'api-stag') {
        $url = "https://api.comprobanteselectronicos.go.cr/recepcion-sandbox/v1/recepcion/";
    } else if (params_get("client_id") == 'api-prod') {
        $url = "https://api.comprobanteselectronicos.go.cr/recepcion/v1/recepcion/";
    }

El que tambien cambia es el del token

    if (params_get("client_id") == 'api-stag') {
        $url = "https://idp.comprobanteselectronicos.go.cr/auth/realms/rut-stag/protocol/openid-connect/token";
    } else if (params_get("client_id") == 'api-prod') {
        $url = "https://idp.comprobanteselectronicos.go.cr/auth/realms/rut/protocol/openid-connect/token";
    }

https://github.com/CRLibre/API_Hacienda/blob/master/api/contrib/token/mhToken.php

**Comment by yusuflimdiwala** [comment]
Hi @walner1borbon  i am trying the same with above mentioned URL , when obtaining token for stagging its working fine but when i am sending invoice, i am getting 403 response with, IncompleteSignatureException , can you advise what i can do to get pass this error ?
