### ISSUE TITLE
Soporte para Docker

### ISSUE THREAD

**Issue by ArcezD** [CRLibre/API_Hacienda#24]
**Describa el problema** *(bug)*
De acuerdo a alguno de los temas que se conversaron en la presentación, sobre la posibilidad de poder ejecutar el API en un contenedor Docker, hice algunas modificaciones para poder ejecutar en un branch. 

https://github.com/ArcezD/API_Hacienda/tree/docker

Actualmente se puede ejecutar mediante el comando "docker-compose up", el mismo ejecuta un server apache con php7.2 y una base de datos MariaDB donde se crean las tablas requeridas.
Los datos de crypto-key, host, usuario y contraseña de base de datos se configuran mediante variables de entorno.
Pero de momento tengo un problema al ejecutar supongo que cualquier llamado sobre las lineas 39 y 40 en el archivo api/core/tools.php, la verdad que PHP no es mi lenguaje principal, les agradezco si me pueden dar alguna pista.

`GET http://localhost/api.php?w=crypto&r=makeKey`

`<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/api/modules/crypto/module.php:1) in
<b>/var/www/api/core/tools.php</b> on line
<b>39</b>
<br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/api/modules/crypto/module.php:1) in
<b>/var/www/api/core/tools.php</b> on line
<b>40</b>
<br />
{"resp":"71O9u5\/M2NGuxKby6x+MeCmSlMQnYx3b1d7TwntUHRs="}`

**Contexto adicional**
Muy buen proyecto! Exitos a todos.

**Comment by ArcezD** [comment]
He logrado resolver el error que mostraba al realizar las consultas, al parecer está relacionado a espacios en blanco antes de la etiqueta `<?php`. https://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php. (Commit: https://github.com/ArcezD/API_Hacienda/commit/cf578533cb79c61b1f4ec464dd4599a022fb5698)

Voy a ejecutar llamados a otros APIS con la finalidad de realizar algunas pruebas antes de validar como satisfactoria la imagen del contenedor Docker.

**Comment by jsubiros1** [comment]
Si, es correcto, esto pasa porque apache envía primero el texto que se encuentra antes de la apertura de php sin haber enviado antes los headers. Entonces tira ese error de que se ha enviado algo antes de que se enviaran los headers que se utilizan.

**Comment by walner1borbon** [comment]
Buenas tardes ya está listo esos errores, si gusta lo puede descargar de nuevo y ya funciona bien

**Comment by mamm26** [comment]
Hola, no se ha recibido más noticias sobre esta incidencia por lo que se entiende que está solucionado, si la incidencia persiste, por favor comentarlo para reabrir.
