### ISSUE TITLE
Notice y Warning al registrar usuario

### ISSUE THREAD

**Issue by RamiroS77** [CRLibre/API_Hacienda#26]
Cuando intento registrar un usuario recibo este error:

```
<br />
<b>Notice</b>:  Undefined variable: key in <b>C:\xampp\AH\api\modules\crypto\crypto.php</b> on line <b>21</b><br />
<br />
<b>Notice</b>:  Undefined variable: key in <b>C:\xampp\AH\api\modules\crypto\crypto.php</b> on line <b>25</b><br />
<br />
<b>Notice</b>:  Undefined variable: key in <b>C:\xampp\AH\api\modules\crypto\crypto.php</b> on line <b>37</b><br />
<br />
<b>Notice</b>:  Undefined variable: key in <b>C:\xampp\AH\api\modules\crypto\crypto.php</b> on line <b>41</b><br />
<br />
<b>Warning</b>:  password_hash() expects at least 2 parameters, 1 given in <b>C:\xampp\AH\api\modules\users\module.php</b> on line <b>352</b><br />
<br />
<b>Notice</b>:  Undefined variable: key in <b>C:\xampp\AH\api\modules\crypto\crypto.php</b> on line <b>21</b><br />
<br />
<b>Notice</b>:  Undefined variable: key in <b>C:\xampp\AH\api\modules\crypto\crypto.php</b> on line <b>25</b><br />
```

Sin embargo crea el usuario y el Session Key.

Soluciono ese problema agregando:

```php
global $key;
```

en cada función de api\modules\crypto\crypto.php.

Pero también está el Warning:

```
<b>Warning</b>:  password_hash() expects at least 2 parameters, 1 given in <b>C:\xampp\AH\api\modules\users\module.php</b> on line <b>352</b><br />
```

Revisando en la documentación, el segundo parámetro es por defecto PASSWORD_DEFAULT. Lo uso y me genera un Session Key bastante largo, pero funciona. 

Lo que si da problemas es que a veces contiene un + y a la hora de hacer logout no lo interpreta bien y le pone un espacio y por eso el query no devuelve  la sesión.

Probando en XAMPP con PHP 7.2.6

**Comment by eliastorres** [comment]
Sobre la línea:

`<b>Warning</b>:  password_hash() expects at least 2 parameters, 1 given in <b>C:\xampp\AH\api\modules\users\module.php</b> on line <b>352</b><br />
`

Se trata de una advertencia en PHP 7: http://php.net/manual/en/function.password-hash.php

> Warning
> The salt option has been deprecated as of PHP 7.0.0. It is now preferred to simply use the salt that is generated by default.

**Comment by eliastorres** [comment]
Esto está relacionado con el issue #20

**Comment by Steven20cr** [comment]
La key la solucione de esta forma:

`function keyval(){
    $key = conf_get('key', 'crypto');
    return $key;
}
`
Asi nada más creo una función que la define y listo

Esta es la llamada:

`$key = keyval();`

**Comment by RamiroS77** [comment]
Gracias! ahi vi que en la última versión la definición de $key ya está adentro de la función.

**Comment by eliastorres** [comment]
Hola @RamiroS77  ¿Podría ayudarnos a verificar de nuevo luego de los cambios realizados por @walner1borbon en #31?

**Comment by RamiroS77** [comment]
Si, confirmo que los cambios solucionaron el problema.
