### ISSUE TITLE
Error al crear usuario en el Api

### ISSUE THREAD

**Issue by Steven20cr** [CRLibre/API_Hacienda#27]
**Al registrar un usuario nuevo en el api, me lanza este error:**

Trying to get property of non-object in /htdocs/facturacr/api/modules/users/module.php on line 268

Este es el código donde aparece

    $newUserByName = users_load(array('userName' => params_get('userName', '')));
    $newUserByEmail = users_load(array('email' => params_get('email', '')));

    if ($newUserByName->idUser == 0 && $newUserByEmail->idUser == 0) {
        grace_debug("New user does not exist");
        $user = _users_register(
                array(
                    "fullName" => params_get('fullName', ''),
                    "userName" => params_get('userName', ''),
                    "email" => params_get('email', ''),
                    "about" => params_get('about', 'May all beings be at ease'),
                    "country" => params_get('country', 'crc'),
                    "status" => 1,
                    "timestamp" => time(),
                    "lastAccess" => time(),
                    "pwd" => params_get('pwd', ''),
                    "avatar" => 0
                )
        );

Por algún motivo no me permite acceder a la propiedad idUser
Al parecer o hay un error en esta llamada o la forma de acceder a la propiedad es incorrecta.

`$newUserByEmail = users_load(array('email' => params_get('email', '')));`
`$newUserByName->idUser`

Alguien que haya dado con algo en esta parte?

**Comment by eliastorres** [comment]
Hola @Steven20cr, ¿Podría probar de nuevo luego de los cambios realizados por @walner1borbon  en #31 ?

**Comment by Steven20cr** [comment]
Hola walner y elias
Es correcto ya no me lanza los errores. 

Aun me falta probar las otras funciones del api pero lo que he probado con walner hasta el momento va bien. 

Estamos en contacto
