### ISSUE TITLE
Error con campos de Base de Datos

### ISSUE THREAD

**Issue by ArcezD** [CRLibre/API_Hacienda#30]
**Describa el problema** *(bug)*
He tenido dos problemas con distintas operaciones al momento de realizar la inserción en base de datos.
Por ejemplo en el caso de la operación para registrar usuario, el campo settings se encuentra como "NOT_NULL", sin embargo al momento de realizar la inserción en base de datos en el archivo api/modules/users/module.php no se envía valor alguno para el campo "settings".
En el caso de subir un certificado .p12 el campo md5 es de solamente 20 caracteres, lo requerido son 32.
Será posible que el archivo .sql para la creación de las tablas se encuentre desactualizado?

**Pasos para reproducir**
Pasos para reproducir
1. Cargar en una base de datos en blanco el script [crlibre_api_Limpia.sql](https://github.com/CRLibre/API_Hacienda/blob/master/recursos/crlibre_api_Limpia.sql)
2. Ejecutar el payload para la creación de un usuario ó la operación para subir un archivo .p12

**Contexto adicional**
Gracias por la ayuda.

**Comment by walner1borbon** [comment]
Hola esos cambios estan en la base de datos
https://github.com/CRLibre/API_Hacienda/blob/master/recursos/api_base.sql

**Comment by walner1borbon** [comment]
Esos campos se actualizaron con la nueva estructura
dado que el tamaño de esos campos aumento

**Comment by walner1borbon** [comment]
Voy a subir una nueva mañana para corregir

**Comment by mamm26** [comment]
Hola, alguno podría confirmar la solución de este problema?

**Comment by base64bits** [comment]
El problema aún continua, acabo de bajar la base de datos nueva y sigue igual, el problema de los usuarios no es tan grave, al menos a mi no me dio errores, pero el problema del campo md5 en files no me guardaba la info del p12 en la base de datos y por ende no me dejaba firmar.

**Comment by base64bits** [comment]
> Hola, alguno podría confirmar la solución de este problema?

Les hice los cambios a la base de datos y a otro archivo para corregir estos errores por su gustan aceptarlos.

**Comment by mamm26** [comment]
> > Hola, alguno podría confirmar la solución de este problema?
> 
> Les hice los cambios a la base de datos y a otro archivo para corregir estos errores por su gustan aceptarlos.

Cuál archivo de SQL usaste para tu DB?

**Comment by base64bits** [comment]
> > > Hola, alguno podría confirmar la solución de este problema?
> > 
> > 
> > Les hice los cambios a la base de datos y a otro archivo para corregir estos errores por su gustan aceptarlos.
> 
> Cuál archivo de SQL usaste para tu DB?

https://github.com/CRLibre/API_Hacienda/blob/master/recursos/api_base.sql

**Comment by base64bits** [comment]
> @base64bits: Si gustas puedes hacer un [issue](https://github.com/CRLibre/API_Hacienda/issues/) utilizando un ALTER a los cambios que recomiendas para mirarlos.

Voy a proceder, pero anoche les hice un pull request con los cambios no se si lo pueden aceptar, sorry soy nuevo en GitHub

**Comment by mamm26** [comment]
@base64bits: Puedes verificarlo? Es que el pull request no está en nuestro repositorio, igualmente Github está teniendo problemas desde ayer con el almacenamiento y está estado dando fallas, que por lo visto no han finalizado aún de reparar.
