### ISSUE TITLE
Monto descuento erroneo en XML

### ISSUE THREAD

**Issue by son1cman** [CRLibre/API_Hacienda#36]
El xml devuelto cuando se usa el campo montodescuento da error en hacienda ya que este se agrega despues de <subtotal> y no antes como deberia de ser.

Pasos para reproducir
Utilizando el ejemplo con las lineas de detalle suministrado en la documentacion del api v1.2 se puede reproducir facilmente dicho error.

**Comment by walner1borbon** [comment]
Voy a hacer la actualización mañana

**Comment by mamm26** [comment]
Hola @son1cman, ¿podrías confirmar si se ha solucionado el problema?

**Comment by mamm26** [comment]
Al parecer este cambio fue realizado en: 3f44e6ecf41a63f5c831d8e921b99a87368fc5eb, cierro el reporte.
