### ISSUE TITLE
[Sugerencia] Orden de trabajo

### ISSUE THREAD

**Issue by mamm26** [CRLibre/API_Hacienda#37]
Buenas, estuve hablando de algunas sugerencias en Colaboradores que me gustaría aplicar en el área de trabajo.

Recordemos ante de todo, que un proyecto _open source_ siempre va dirigido a todo el público que tenga interés en el proyecto (ya sea para uso o colaborar), es por eso que es **importante** que el proyecto tenga una imagen más clara y limpia posible es por ello que vengo a sugerir que se deben hacer unos cambios de codestyle, eliminar whitespaces y hacer un cambio de tabulaciones por espacios (tab2space). 

### Codestyle

La idea es regirnos más que nada por el estándar de codestyle de Google (https://google.github.io/styleguide/). Voy a dar unos ejemplos para que sea más claro de lo que me refiero dando ejemplos de modos incorrectos y correctos.

**Whitespaces:**

No se deben colocar espacios adentro del paréntesis.
Se debe colocar el espacio antes del paréntesis, no después.

❌ Incorrecto
```php
if( $hacienda )
if ( $hacienda )
```

✔️  Correcto
```php
if ($hacienda)
```

**Llaves:**

Se deben utilizar las llaves de forma simétrica, y en caso de que haya una sola línea no es necesario las llaves.

❌ Incorrecto
```php
if ($hacienda) {
   $certificado = true;
   $token = true;
}
else{
    $certificado = false;
}
```

✔️  Correcto
```php
if ($hacienda)
{
   $certificado = true;
   $token = true;
}
else
    $certificado = false;
```

En el caso de los _loops_ exactamente lo mismo:

✔️  Correcto
```php
for ($i = 0; $i < 0; ++$i)
{
   algunaFuncion();
   otraFuncion();
}

$i = 0;
while ($i < 10)
{
   algunaFuncion();
   otraFuncion();
   ++$i;
}
```

**Números mágicos y constantes:**

Las constantes hacen que sea más fácil de comprender el código.

❌ Incorrecto
```php
if (getToken() == 1)
   funcionCorrecto();
```

✔️  Correcto
```php
if (getToken() == TOKEN_RESULT_OK)
   funcionCorrecto();
```

Por lo que siempre debemos hacer las definiciones:
```php
define('TOKEN_RESULT_ERROR', 0);
define('TOKEN_RESULT_OK', 1);
```

### Tab2spaces

La idea es mantener siempre el código con espacios para que sea lo mayor comprensible en la web de Github, es decir, eliminar las tabulaciones, a continuación doy un ejemplo de como se ve en nuestro editor y como se ve en Github. Lo más recomendable es buscar en el Editor que usamos si es posible cambiar las tabulaciones a espacios de forma automática.

**Nuestro editor:**
```php
// Espacios
function obtenerLlave()
{
   $algo;
}

// Tabulaciones
function obtenerLlave()
{
   $algo;
}

```

**Github:**

```php
// Espacios
function obtenerLlave()
{
   $algo;
}

    // Tabulaciones
    function obtenerLlave()
    {
       $algo;
    }
```

Espero que sea aprobada y de ser así, yo le echaría un ojo para tratar de hacer los cambios en el API y así, poder colaborar con el proyecto.

**Comment by walner1borbon** [comment]
Perfecto esperame a subir mañana un update de todo y empezamos desde ahí!

**Comment by mamm26** [comment]
Se trabajarán los cambios desde aquí: #42
