### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by moncada1991** [CRLibre/API_Hacienda#45]
He instalado el API en otro servidor, los modulos de Creacion de Usuario, Login, LogOut, Generacion de Token y Resfresh Token sirven a la perfección, pero al momento de generar el la clave para firmar los XML lanza el error que no encuentra el modulo

Pasos para reproducir
1. Hacer una peticion POST a http://HOST/API_Hacienda/www/api.php
2. Mis parametros son : 
[{"key":"w","value":"clave","description":""},{"key":"r","value":"clave","description":""},{"key":"tipoCedula","value":"juridico","description":""},{"key":"cedula","value":"3101672378","description":""},{"key":"situacion ","value":"nomal","description":""},{"key":"codigoPais","value":"506","description":""},{"key":"consecutivo","value":"60","description":""},{"key":"codigoSeguridad","value":"98459654","description":""},{"key":"tipoDocumento","value":"FE","description":""},{"key":"terminal","value":"00001","description":""},{"key":"sucursal","value":"001","description":""}]

Adicional, he revisado que el modulo exista, y efectivamente ahi se encuentra y con su nombre respectivo. Tambien que el proyecto se bajo el dia 01 de Octubre del 2018 del repositorio actual y del branch master.

![bug](https://user-images.githubusercontent.com/37302586/46386900-5ab9b180-c681-11e8-996e-57c77eb59897.png)

**Comment by mamm26** [comment]
Hola, ¿podrías indicar bajo cuál Sistema operativo estás corriendo el API?

**Comment by moncada1991** [comment]
Actualmente lo estoy corriendo de forma local en window con XAMP, encontré que el modulo existe pero si la petición se realiza por GET en vez de POST, contrario a lo que se indica en la doc.

**Comment by moncada1991** [comment]
Lo probé y ya me funciona cuando se ejecuta de forma local utilizando XAMP
