### ISSUE TITLE
Error con la firma digital xades-epes

### ISSUE THREAD

**Issue by apokalipto** [CRLibre/API_Hacienda#5]
La firma no es válida. Aquí adjunto los pasos que he estado siguiendo, para corroborar si a ustedes les sucede lo mismo cuando intenan firmar el documento.

Primero para efectos prácticos, hice un script en PHP para encapsular la funcionalidad del Firmador, y poder firmar el XML desde la línea de comando.

```php
<?php
	include 'Firmadohaciendacr.php';
	
	$cert = $argv[1];
	$pin = $argv[2];
	$xmlIn = $argv[3];
	$xmlOut = $argv[4];
	
	$signer = new Firmadocr();
	echo "Certificado: " . $cert . "\n";
	echo "PIN: " . $pin .  "\n";
	echo "IN: " . $xmlIn . "\n";
	echo "OUT: " . $xmlOut . "\n";

	$signer->firmar($cert,$pin,$xmlIn,$xmlOut);
	
?>
```
Los pasos concretos para reproducir el error: 

1. Generar el XML: https://gist.github.com/apokalipto/f7697db0bedab130d3f78f4d4d4000b0
2. Firmar XML: `php -q firmar.php  <keyPath> <keyPassword> <xmlInPath> <xmlOutPath>`
3. Enviar documento firmado al API. Respuesta => HTTP 202 (estado aceptado)
4. Hacer query para verificarlo: GET "https://api.comprobanteselectronicos.go.cr/recepcion-sandbox/v1/recepcion/50609021800011190015800100001010000000023199999999"

La respuesta es la siguiente:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<MensajeHacienda xmlns="https://tribunet.hacienda.go.cr/docs/esquemas/2016/v4.1/mensajeHacienda">
    <Clave>50609021800011190015800100001010000000023199999999</Clave>
    <NombreEmisor/>
    <TipoIdentificacionEmisor>02</TipoIdentificacionEmisor>
    <NumeroCedulaEmisor> 3102111111 </NumeroCedulaEmisor>
    <NombreReceptor/>
    <TipoIdentificacionReceptor>02</TipoIdentificacionReceptor>
    <NumeroCedulaReceptor>3001123208</NumeroCedulaReceptor>
    <Mensaje>3</Mensaje>
    <DetalleMensaje>Este comprobante fue procesado en el ambiente de pruebas, por lo cual no tiene validez para fines tributarios.

La firma del comprobante electrónico no es válida</DetalleMensaje>
```

Les comento que he estado teniendo el mismo problema con varias soluciones. También con implementaciones en Java:

- https://github.com/johann04/xades-signer-cr
- https://github.com/jonhcr/firmaxadesepes
- Una implementación propia utilizando todo lo expuesto en: 
https://github.com/luisgoncalves/xades4j/issues/134

Saben que podría estar pasando? A ustedes les da el mismo error? De antemano se les agradecen sus comentarios.

**Comment by rvargasp** [comment]
Ya intentó cambiando la versión del esquema en la URL a 4.2?

**Comment by apokalipto** [comment]
El problema no era con la firma. El problema era con el XML, y su codificación en base64 a la hora de enviarlo. La respuesta de rechazo  debido a que "la firma del comprobante electrónico no es válida, NO NECESARIAMENTE se refiere a la firma digital en sí. Puede estar asociada a problemas con el XML. Adjunto algunas de las posibles causas.

- Verificar que la calve esté correcta
    - La sección H puede contener un número aleatorio o elegido por el desarrollador.
- Verificar que el consecutivo de la clave coincida con el consecutivo del XML
- Verificar que la fecha de emisión cumpla con el estandar RFC3339: Ej: `2018-02-12T04:05:06-07600`
- Verificar que a la hora de serializar el XML en Base64, no contenga los cambios de linea ("\n")
- Verificar que la ubicación del emisor coincida con los registros de hacienda
- Verificar los namespaces del XML: 
```xml
<FacturaElectronica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica" xsi:schemaLocation="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica.xsd">
```

**Comment by lurobaca** [comment]
creo que me contesto solo, si no me equivoco los parámetros para firmar los obtenemos a a la hora de obtener el usuario y contraseña del ATV, primero vamos a ATV https://www.hacienda.go.cr/atv/login.aspx

luego seguimos los pasos para obtener el certificado digital llengo al menu COMPROBANTE ELECTRONICO/LLAVE CRIPTOGRAFICA DE PRUEBA/GENERAR LLAVE CRIPTOGRAFICA .

después de llenar la información del formulario con el PIN que solicita el cual colocamos en el parámetros $pinP12  y descargar el archivo que lleva como nombre la cedula del contribuyente , emisor y o persona que necesita el usuario y clave del atv y este archivo lleva extencion .p12 ejem:  310120005785.p12 el cual necesitamos guardar y luego debemos indicar la ruta de ese archivo en el parematro $p12Url  . los otros 2 parámetros imagino que es mas fácil identificarlos, el parámetros $xmlIn  solo es la ruta donde tenemos el XML que deseamos firmar y $xmlOut es la ruta donde se almacenara el xml ya firmado o al menos eso es lo que entiendo


`function signFE(){
        require 'Firmadohaciendacr.php';

        modules_loader("files");  

        $p12Url= filesGetUrl(params_get('p12Url')); //Url del Servidor donde esta el certificado con extencion .p12 este archivo se consigue en el ATV de hacienda, es el que se descarga a la hora de generar la llave criptografica y antes de generar el usuario y clave del ATV
     
   $pinP12= params_get('pinP12'); //Pin del certificado, este el el pin que solicita la llave criptografica cuando ejecutamos el archivo .p12 que descargamos de ATV
     
   $inXmlUrl= filesGetUrl(params_get('inXmlUrl')); //URL en el servidor donde esta el XML que se va a firmar
        
  $outXmlUrl= params_get('outXmlUrl');//almacena la URL donde se almacena el XML con la firma
     
   $tipodoc=params_get('tipodoc');// URL en el servidor donde va a salir el XML firmado
        
        $fac = new Firmadocr();        
        $fac->firmar($p12Url, $pinP12,$inXmlUrl,$outXmlUrl,$tipodoc );
        
        return $outXmlUrl;
}
?>`

**Comment by lurobaca** [comment]
eso a mi me paso y lo corregi revisa los encabezados de cada documento,
todos los xml son iguales lo unico que varia son los encabezados y el tag
de cierre, en CRLibre whatsapp publicaron una clase en php con cada
encabezado, te lo pasaria pero ahorita estoy fuera de la compu,puede ser
eso, algun espacio mal dado o enter mal dado.
o usuarios y clave;de ATV malos , podrias volverlos a generar y volver a
instalar el archivo .p12

**Comment by asegurabadilla** [comment]
@lurobaca gracias por su respuesta. Este es el encabezado que estoy utilizando.
<?xml version="1.0" encoding="UTF-8"?>
<FacturaElectronica xmlns="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica.xsd">

Además cuando se codifica a Base64, también lo he echo como indica @apokalipto sin retornos de carro(\n). 
Estoy utilizando xades4j el código de @edennish.

**Comment by jparajeles** [comment]
Han encontrado una soluccion sobre este tema, me muestra un error al enviar el xml: 

#:SSL certificate problem: unable to get local issuer certificate

Saludos

**Comment by nayrban** [comment]
Alguno tiene un ejemplo de un documento valido que hayan probado contra staging?
Este es lo genero yo, pero de igual forma no es valido para hacienda.
[https://drive.google.com/file/d/1fNkX61Dd2ECvPEyY_hrYDswtJhbW8WoR/view?usp=sharing](Documento Firmado)

Lo validamos contra https://apis.gometa.org/validar/ y es valido, 
la verdad no tenemos idea xq hacienda retorna ese error de manera generica

Cambiamos el formato de la fecha, corregimos unos montos, encabezados como los que mencionan arriba.
Pero no tenemos la menor idea

**Comment by nehemiascr** [comment]
Me sucedió el mismo problema, al xml le faltaba la declaración de xml
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
```
estaba codificando en base64 el string
```xml
<FacturaElectronica xmlns="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xsi:schemaLocation="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica  https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/FacturaElectronica_V.4.2.xsd">
  <Clave>
```
el lugar de codificar el string con la declaración de xml
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<FacturaElectronica xmlns="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xsi:schemaLocation="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica  https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/FacturaElectronica_V.4.2.xsd">
  <Clave>
```

Ya no me da el problema :)
