### ISSUE TITLE
respuesta hacienda

### ISSUE THREAD

**Issue by crodriguez82** [CRLibre/API_Hacienda#50]
**Describa el problema** *(bug)*
El xml se envía hacienda y al recibir la respuesta llega con el siguiente mensaje

<Mensaje>1</Mensaje>
    <DetalleMensaje>Este comprobante fue aceptado en el ambiente de pruebas, por lo cual no tiene validez para fines tributarios

codigo, mensaje, fila, columna
-16, "El archivo XML, fue enviado a la Dirección General de Tributación de manera extemporánea; con base en lo estipulado en el artículo 9 y 15 ambos de la resolución 48-2016", 0, 0
</DetalleMensaje>
    <MontoTotalImpuesto>1235.0</MontoTotalImpuesto>
    <TotalFactura>10735.0</TotalFactura>
<ds:Signature Id="id-cda79b81915393e5169f954a52fb7555" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Referenc

**Pasos para reproducir**
Pasos para reproducir
Se solicita la creación de la clave y firma de documento, se envía hacienda desde odoo

**Comportamiento esperado**
Lo que debería pasar.

**Capturas de pantalla o registro de bitácora**
Si aplica, por favor adjuntar capturas o registros de logs con mensajes de error.

![error](https://user-images.githubusercontent.com/29420191/47060924-a80f4600-d18c-11e8-922e-1ab69c2b86c0.png)

**Contexto adicional**
Cualquier otro contexto acá.

**Comment by dceevp** [comment]
Ese mensaje aparece comúnmente cuando el documento que intentas aceptar ha superado el tiempo de 8 días hábiles para realizar la aceptación. ¿Podrías verificar la fecha de emisión del documento que estas aceptando?

**Comment by base64bits** [comment]
En nuestra experiencia este mensaje lo envía hacienda cuando la fechaEmsion del documento que se envía tiene una fecha diferente a la fecha actual, ósea se manda una factura hoy con fecha de ayer o antes, Hacienda la acepta pero notifica que se está enviando con una fecha anterior

**Comment by mamm26** [comment]
@crodriguez82: Como bien dicen anteriormente, ¿podrías verificar esa información en el archivo XML que envíaste a Hacienda?

**Comment by crodriguez82** [comment]
Si ya cambie la zona horaria en mi servidor, ahora hice pruebas y funciono normal. Gracias por su ayuda, a nivel del API sabe si este cumple al tomar en su código la zona horaria que lleva America/Costa_Rica o lo toma del servidor?

**Comment by mamm26** [comment]
@crodriguez82: Actualmente es sólo por parte del servidor, voy a añadir que se cambie automáticamente, gracias.

**Comment by crodriguez82** [comment]
Gracias a ti mi estimado
