### ISSUE TITLE
Error emisor desconocido en respuesta de hacienda

### ISSUE THREAD

**Issue by crodriguez82** [CRLibre/API_Hacienda#53]
**Describa el problema** *(bug)*
El comprobante xml se llena todos los campos de forma correcta

la respuesta de hacienda trae lo siguiente 

<MensajeHacienda xmlns="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda">
<Clave>50618101800020577039400100001010000000008103185677</Clave>
<NombreEmisor>DESCONOCIDO</NombreEmisor>
<TipoIdentificacionEmisor>01</TipoIdentificacionEmisor>
<NumeroCedulaEmisor>000000000</NumeroCedulaEmisor>
<Mensaje>3</Mensaje>
<DetalleMensaje>
El comprobante electrónico tiene los siguientes errores: [ codigo, mensaje, fila, columna -1, "cvc-enumeration-valid: Value 'False' is not facet-valid with respect to enumeration '[01, 02, 03, 04]'. It must be a value from the enumeration.", 26, 39 ]
</DetalleMensaje>
<MontoTotalImpuesto>0</MontoTotalImpuesto>
<TotalFactura>0</TotalFactura>
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="id-ca8746e4c110c4a0dd6841ac562a5608">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
<ds:Reference Id="r-id-1" Type="" URI="">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
<ds:XPath>not(ancestor-or-self::ds:Signature)</ds:XPath>
</ds:Transform>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>nlN4Tvf9CI3Uoy9diobc4YynLR1Xzj2Hnr8lkBXfIB0=</ds:DigestValue>
</ds:Reference>
<ds:Reference Type="http://uri.etsi.org/01903#SignedProperties" URI="#xades-id-ca8746e4c110c4a0dd6841ac562a5608">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>5XuoLc77GQY8lLK39nis1ZnJ6fGgS1iN9zBPRVY8GrQ=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue Id="value-id-ca8746e4c110c4a0dd6841ac562a5608">
XGEaizU3anPT5gUyEcj6bB/qtWTMws2GlzBmYRLgdtjnongBvxXEt9nvdwWuwP778VyJO1Tq1SpNSVXYkCYRcqW4Q0HtNjMLDwvp9XoJ06bnhkAr5ZJWB4R10jJ/hha7j9u9eVLMLcUqE/O4jftqniIXcc+dBruEj2dmkwLWObp2A6qgKbWcFN2r61QoleYGhe4uGCTpMMNBhNZZvm2ekZnah2O3fmAvTkBrRDUaZiVUiCisWaQFDDi2VB5iW/S2PdWjolPcmGN7GQQpTPVDlEE1DYsbTnwjY/8kfyTfh0g+9LtxJlPDTnbW5w9H+67TVxWH6X4cGI5rp5w2VdJACg==
</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
MIIMATCCCemgAwIBAgITcAAAAAS1EASHql+FwQAAAAAABDANBgkqhkiG9w0BAQ0FADB/MRkwFwYDVQQFExBDUEotMi0xMDAtMDk4MzExMQswCQYDVQQGEwJDUjEPMA0GA1UEChMGTUlDSVRUMQ0wCwYDVQQLEwREQ0ZEMTUwMwYDVQQDEyxDQSBQT0xJVElDQSBQRVJTT05BIEpVUklESUNBIC0gQ09TVEEgUklDQSB2MjAeFw0xNTA3MjkxODA0NDlaFw0yMzA3MjkxODE0NDlaMIGbMRkwFwYDVQQFExBDUEotNC0wMDAtMDA0MDE3MQswCQYDVQQGEwJDUjEkMCIGA1UEChMbQkFOQ08gQ0VOVFJBTCBERSBDT1NUQSBSSUNBMSIwIAYDVQQLExlESVZJU0lPTiBTSVNURU1BUyBERSBQQUdPMScwJQYDVQQDEx5DQSBTSU5QRSAtIFBFUlNPTkEgSlVSSURJQ0EgdjIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDS0O9o2R2AUytRVXzLD+l1tPTMaGSNL5tTtXj3OlAgYl2D9TouG2oeSvgOrKwKULrbGBfhRmWvNr/4PZ7iTq/l2N1jYa2kMbPchZouohjIfObhXtJ5yEUZFO0L4HC1th+FWee08+rDnReu1vGuhG47Sjf8pryqqBMNiYlD1MIchFcH9dWvLXsqBjH0qZZMtjpuUUTIvrLHG0wf5Esa+4ZrpObygEA8hMTJJD5gxmZEDTmsi0voP/MWR5mKDmm2QMuIkNpb7KMb4NdbiAptqFtk8WSiTFp9ALMi0ZuKkxOg87zK1UHQy0Jn3Kh8uba1s/d9sJaFafhgD3SooPcN28sNAgMBAAGjggdXMIIHUzAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUiCT863HSccmoWbILf5TcT4Ra2tIwggTKBgNVHSAEggTBMIIEvTCB4QYHYIE8AQEBATCB1TCBpgYIKwYBBQUHAgIwgZkegZYASQBtAHAAbABlAG0AZQBuAHQAYQAgAGwAYQAgAFAAbwBsAO0AdABpAGMAYQAgAGQAZQAgAGwAYQAgAFIAYQDtAHoAIABDAG8AcwB0AGEAcgByAGkAYwBlAG4AcwBlACAAZABlACAAQwBlAHIAdABpAGYAaQBjAGEAYwBpAPMAbgAgAEQAaQBnAGkAdABhAGwAIAB2ADIwKgYIKwYBBQUHAgEWHmh0dHA6Ly93d3cuZmlybWFkaWdpdGFsLmdvLmNyADCCASMGCGCBPAEBAQEBMIIBFTCB5gYIKwYBBQUHAgIwgdkegdYASQBtAHAAbABlAG0AZQBuAHQAYQAgAGwAYQAgAFAAbwBsAO0AdABpAGMAYQAgAGQAZQAgAEMAQQAgAEUAbQBpAHMAbwByAGEAIABwAGEAcgBhACAAUABlAHIAcwBvAG4AYQAgAEoAdQByAO0AZABpAGMAYQAgAHAAZQByAHQAZQBuAGUAYwBpAGUAbgB0AGUAIABhACAAbABhACAAUABLAEkAIABOAGEAYwBpAG8AbgBhAGwAIABkAGUAIABDAG8AcwB0AGEAIABSAGkAYwBhACAAdgAyMCoGCCsGAQUFBwIBFh5odHRwOi8vd3d3LmZpcm1hZGlnaXRhbC5nby5jcgAwggFUBghggTwBAQEBBjCCAUYwggEWBggrBgEFBQcCAjCCAQgeggEEAEkAbQBwAGwAZQBtAGUAbgB0AGEAIABsAGEAIABQAG8AbADtAHQAaQBjAGEAIABwAGEAcgBhACAAQwBlAHIAdABpAGYAaQBjAGEAZABvAHMAIABkAGUAIABTAGUAbABsAG8AIABFAGwAZQBjAHQAcgDzAG4AaQBjAG8AIABkAGUAIABQAGUAcgBzAG8AbgBhACAASgB1AHIA7QBkAGkAYwBhACAAcABlAHIAdABlAG4AZQBjAGkAZQBuAHQAZQAgAGEAIABsAGEAIABQAEsASQAgAE4AYQBjAGkAbwBuAGEAbAAgAGQAZQAgAEMAbwBzAHQAYQAgAFIAaQBjAGEAIAB2ADIwKgYIKwYBBQUHAgEWHmh0dHA6Ly93d3cuZmlybWFkaWdpdGFsLmdvLmNyADCCAVYGCGCBPAEBAQEHMIIBSDCCARgGCCsGAQUFBwICMIIBCh6CAQYASQBtAHAAbABlAG0AZQBuAHQAYQAgAGwAYQAgAFAAbwBsAO0AdABpAGMAYQAgAHAAYQByAGEAIABDAGUAcgB0AGkAZgBpAGMAYQBkAG8AcwAgAGQAZQAgAEEAZwBlAG4AdABlACAARQBsAGUAYwB0AHIA8wBuAGkAYwBvACAAZABlACAAUABlAHIAcwBvAG4AYQAgAEoAdQByAO0AZABpAGMAYQAgAHAAZQByAHQAZQBuAGUAYwBpAGUAbgB0AGUAIABhACAAbABhACAAUABLAEkAIABOAGEAYwBpAG8AbgBhAGwAIABkAGUAIABDAG8AcwB0AGEAIABSAGkAYwBhACAAdgAyMCoGCCsGAQUFBwIBFh5odHRwOi8vd3d3LmZpcm1hZGlnaXRhbC5nby5jcgAwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHwYDVR0jBBgwFoAUV7eG/2gnBhlj6878UhGVpyJ4FO0wge4GA1UdHwSB5jCB4zCB4KCB3aCB2oZoaHR0cDovL3d3dy5maXJtYWRpZ2l0YWwuZ28uY3IvcmVwb3NpdG9yaW8vQ0ElMjBQT0xJVElDQSUyMFBFUlNPTkElMjBKVVJJRElDQSUyMC0lMjBDT1NUQSUyMFJJQ0ElMjB2Mi5jcmyGbmh0dHA6Ly93d3cubWljaXQuZ28uY3IvZmlybWFkaWdpdGFsL3JlcG9zaXRvcmlvL0NBJTIwUE9MSVRJQ0ElMjBQRVJTT05BJTIwSlVSSURJQ0ElMjAtJTIwQ09TVEElMjBSSUNBJTIwdjIuY3JsMIIBAgYIKwYBBQUHAQEEgfUwgfIwdAYIKwYBBQUHMAKGaGh0dHA6Ly93d3cuZmlybWFkaWdpdGFsLmdvLmNyL3JlcG9zaXRvcmlvL0NBJTIwUE9MSVRJQ0ElMjBQRVJTT05BJTIwSlVSSURJQ0ElMjAtJTIwQ09TVEElMjBSSUNBJTIwdjIuY3J0MHoGCCsGAQUFBzAChm5odHRwOi8vd3d3Lm1pY2l0LmdvLmNyL2Zpcm1hZGlnaXRhbC9yZXBvc2l0b3Jpby9DQSUyMFBPTElUSUNBJTIwUEVSU09OQSUyMEpVUklESUNBJTIwLSUyMENPU1RBJTIwUklDQSUyMHYyLmNydDANBgkqhkiG9w0BAQ0FAAOCAgEAjyzmz4HkwPv3ZspgsjAC7oRajwSjJjNgBZ+uNoKNWCjUsAa/E9HHw+HY468dRXSsDRpEM717eT7an8WJuqtOrG+JLcGyXKLkzdZVccl9I0qMXXWxyKEcB9UdW7M+mcPNbvXAj3lQcPWwHT3HvKEfAs8be4hqyyKUAny2vJBXFgAusWYIcydTsv7Y0EKipK/NMKALR7DDLMzJFc+bQC8HYtzx96SmgGlWX1zG36Aid9pFu6z/Ml6MVx4OWwr9DvrDuAiO+7RGYszRiJ+GbpbdBDvybfPwv4fs35PBYVpQt+T9e9+aAdeRMB6t3Pcr220MF4B911JB6NRY7jsyQpicXC3zsN8LZIFwJDkRiTeQ4ewN+b04JsOpmNufSKmgfu/D1H5x2C2d30Ct9cfju12E8iPY+XMT6iqFWk9THQnXBWF2GJdci85KW1QkSFosTOxwdeFTdmrn0xDFVDIJ0eQfTCmjY5uT2Xva99f5R0CYawpWyFGz9Dqjmpve60sLSHEk08qo1mnf8OOVLOIjKrgKNRsCHbWC85FfZ+v3vh4SIDEI4NiWplOFnI7GngFG8A+A8AfD5t7t8i47yWvnNcOlHdNaSJkhanGOrhnJsRecKh6WU3qso1HRXn5o6M8hec123HQNVVW0zXxI+NtY9vKqDkGpNgkPbCXgQXJM5ZB5/d8=
</ds:X509Certificate>
<ds:X509Certificate>
MIIFgTCCBGmgAwIBAgITSAAAAIDhYqyfvhB5HQAAAAAAgDANBgkqhkiG9w0BAQsFADCBmzEZMBcGA1UEBRMQQ1BKLTQtMDAwLTAwNDAxNzELMAkGA1UEBhMCQ1IxJDAiBgNVBAoTG0JBTkNPIENFTlRSQUwgREUgQ09TVEEgUklDQTEiMCAGA1UECxMZRElWSVNJT04gU0lTVEVNQVMgREUgUEFHTzEnMCUGA1UEAxMeQ0EgU0lOUEUgLSBQRVJTT05BIEpVUklESUNBIHYyMB4XDTE3MDMxNzE3MTEyOFoXDTIxMDMxNjE3MTEyOFowfzEZMBcGA1UEBRMQQ1BKLTItMTAwLTA0MjAwNTELMAkGA1UEBhMCQ1IxGTAXBgNVBAoTEFBFUlNPTkEgSlVSSURJQ0ExOjA4BgNVBAMTMUVTVEFETy1NSU5JU1RFUklPIERFIEhBQ0lFTkRBIChTRUxMTyBFTEVDVFJPTklDTykwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCqKvf8+SR2Q0I1OexmCTvEL0GedI3ar+sSjWVdC3E7Pad74WmC0HfToE1EzIi/B2tZ7/6VcMlQZdnpsz/onuEqK3kbkxLm2pFxKxfJkAMyWWMVuBexTiMH8B+DVdmQPM6WYeqp/2o43uw3caGltrbAiLfCoqk3OtnW6dNw9HPhEllKZ6KBvPGb9FNrjGJamPEM+O3MtW5bct7MjNZQtPcBH/zLDVVSGcBFFzkQYQox6ApGnhXDIM6LWeJ4xdFs3Je3E1bv63zkzycXTA15/aORYAbkYJ0WHb+xUMEnKUaI0qAss1uTpTpArbl6x0dfICi7wmnzdMD4rwAFZ6y79IXbAgMBAAGjggHXMIIB0zAOBgNVHQ8BAf8EBAMCBsAwHQYDVR0OBBYEFD2RO4EElB22enuTwo3MdkLpW7CYMB8GA1UdIwQYMBaAFIgk/Otx0nHJqFmyC3+U3E+EWtrSMGAGA1UdHwRZMFcwVaBToFGGT2h0dHA6Ly9mZGkuc2lucGUuZmkuY3IvcmVwb3NpdG9yaW8vQ0ElMjBTSU5QRSUyMC0lMjBQRVJTT05BJTIwSlVSSURJQ0ElMjB2Mi5jcmwwgZcGCCsGAQUFBwEBBIGKMIGHMFsGCCsGAQUFBzAChk9odHRwOi8vZmRpLnNpbnBlLmZpLmNyL3JlcG9zaXRvcmlvL0NBJTIwU0lOUEUlMjAtJTIwUEVSU09OQSUyMEpVUklESUNBJTIwdjIuY3J0MCgGCCsGAQUFBzABhhxodHRwOi8vb2NzcC5zaW5wZS5maS5jci9vY3NwMDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQBgjcVCIXE6luC0eM1lZEbgvmXGIaly2uBf4GQhnXeslwCAWQCAQcwEwYDVR0lBAwwCgYIKwYBBQUHAwQwGwYJKwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDBDAVBgNVHSAEDjAMMAoGCGCBPAEBAQEGMA0GCSqGSIb3DQEBCwUAA4IBAQAS+HfJOwdhlCIVSiMucE2oU7oG/xrH/9MQYIHDF8swsgGuvohjDGoiryKP/Tbkdv81KuPGSSYtiumsDVzT9SKLNLHLOGPC22QOQKk8jsW7wjPvCi/HMv+m3+28X9G5u11TK3Qdo2d1Z/trjh7iIyQOaA8JBKwY9mh06GZ7R7ptq/RVOaviRsKhr/510u/7Mh7OoZVVDstxB8L2pyv7WwjqVeYIF9oneLnb25cJdfANILtjIBtRUC1pqSPnVKhj/sdkuK3RlsOEHR7e4XWJtd8DnT48VZy7m3pTveki8us7HFg5TltcgoLqKmfdRT6U/2yb+4qpWZuz0VgubCU8oWdq
</ds:X509Certificate>
<ds:X509Certificate>
MIINajCCC1KgAwIBAgITTgAAAAPe8aFuD8fvBQAAAAAAAzANBgkqhkiG9w0BAQ0FADBzMRkwFwYDVQQFExBDUEotMi0xMDAtMDk4MzExMQ0wCwYDVQQLEwREQ0ZEMQ8wDQYDVQQKEwZNSUNJVFQxCzAJBgNVBAYTAkNSMSkwJwYDVQQDEyBDQSBSQUlaIE5BQ0lPTkFMIC0gQ09TVEEgUklDQSB2MjAeFw0xNTAyMjUyMTExMzdaFw0zMTAyMjUyMTIxMzdaMH8xGTAXBgNVBAUTEENQSi0yLTEwMC0wOTgzMTExCzAJBgNVBAYTAkNSMQ8wDQYDVQQKEwZNSUNJVFQxDTALBgNVBAsTBERDRkQxNTAzBgNVBAMTLENBIFBPTElUSUNBIFBFUlNPTkEgSlVSSURJQ0EgLSBDT1NUQSBSSUNBIHYyMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAw7ZqnDhzsdWRPXbKzYpLMyIFCxH8wMDlbUZp5yD2/pMB6YMGH/8kjEW6A04+2bHN2iU/2SLJbu5NJ8AkCLsJ9vl8AGXFW0y2USUg1n5tj9TlQJ49DcFFJ/Fb9Kbg6baAesALXjqbszZsicUjzpd7pOtbHocz0Mk3cHz6ZYw7zQrDKBlCaKDBlvJK53J+xIvMAqgD9NMmfrY7NJrdksldy7zC9c9WaCRpl0kYeC/y4BvbrWMf1Mu8EpZcF6oP2OP+vlCJQf0udA1cHlAtksZe8yENQG4BeLUGHWyAkEO9e8wFbylGukvUZVJqBuxysGEf30JH6TwcJYZw4FLorQu6ain3TapSFdWsYzhRTIDbUOjm7A4TiEM/vrsSsfJEEhB/v36fnbYjogsPUdowYFq6afh1G+LO1hy/43U8lnqwpnVeOQ710nKK0TJogCKLgnAJbZsUSyEc/C3fnibNwuFnXInKuNTn/PF/UkpqXVEySvi9iZKYrGbPVfM8fTyEBPTMW3xq8Ldav4komr98jjSnZlpzVnQKqo1Ti5MwLUzLr6OXSmV7Do37gPjydJFWZ7TbvcAQBhYgRhj9WFcNO+MG9nUsRn6UhS7E4nPX51At8Ehu95TZ+JH2bzIooiuX7TTlFWnDFlaHhzmN+vhAfgph6iKtLTXSR8LKNMqtpMujW9UCAwEAAaOCB+kwggflMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRXt4b/aCcGGWPrzvxSEZWnIngU7TCCBZgGA1UdIASCBY8wggWLMIIBFAYHYIE8AQEBATCCAQcwgaYGCCsGAQUFBwICMIGZHoGWAEkAbQBwAGwAZQBtAGUAbgB0AGEAIABsAGEAIABQAG8AbABpAHQAaQBjAGEAIABkAGUAIABsAGEAIABSAGEAaQB6ACAAQwBvAHMAdABhAHIAcgBpAGMAZQBuAHMAZQAgAGQAZQAgAEMAZQByAHQAaQBmAGkAYwBhAGMAaQBvAG4AIABEAGkAZwBpAHQAYQBsACAAdgAyMCoGCCsGAQUFBwIBFh5odHRwOi8vd3d3LmZpcm1hZGlnaXRhbC5nby5jcgAwMAYIKwYBBQUHAgEWJGh0dHA6Ly93d3cubWljaXQuZ28uY3IvZmlybWFkaWdpdGFsADCCAVkGCGCBPAEBAQEBMIIBSzCB6gYIKwYBBQUHAgIwgd0egdoASQBtAHAAbABlAG0AZQBuAHQAYQAgAGwAYQAgAFAAbwBsAGkAdABpAGMAYQAgAGQAZQAgAEMAQQAgAEUAbQBpAHMAbwByAGEAIABwAGEAcgBhACAAUABlAHIAcwBvAG4AYQBzACAASgB1AHIAaQBkAGkAYwBhAHMAIABwAGUAcgB0AGUAbgBlAGMAaQBlAG4AdABlACAAYQAgAGwAYQAgAFAASwBJACAATgBhAGMAaQBvAG4AYQBsACAAZABlACAAQwBvAHMAdABhACAAUgBpAGMAYQAgAHYAMjAqBggrBgEFBQcCARYeaHR0cDovL3d3dy5maXJtYWRpZ2l0YWwuZ28uY3IAMDAGCCsGAQUFBwIBFiRodHRwOi8vd3d3Lm1pY2l0LmdvLmNyL2Zpcm1hZGlnaXRhbAAwggGGBghggTwBAQEBBjCCAXgwggEWBggrBgEFBQcCAjCCAQgeggEEAEkAbQBwAGwAZQBtAGUAbgB0AGEAIABsAGEAIABQAG8AbABpAHQAaQBjAGEAIABwAGEAcgBhACAAQwBlAHIAdABpAGYAaQBjAGEAZABvAHMAIABkAGUAIABTAGUAbABsAG8AIABFAGwAZQBjAHQAcgBvAG4AaQBjAG8AIABkAGUAIABQAGUAcgBzAG8AbgBhACAASgB1AHIAaQBkAGkAYwBhACAAcABlAHIAdABlAG4AZQBjAGkAZQBuAHQAZQAgAGEAIABsAGEAIABQAEsASQAgAE4AYQBjAGkAbwBuAGEAbAAgAGQAZQAgAEMAbwBzAHQAYQAgAFIAaQBjAGEAIAB2ADIwKgYIKwYBBQUHAgEWHmh0dHA6Ly93d3cuZmlybWFkaWdpdGFsLmdvLmNyADAwBggrBgEFBQcCARYkaHR0cDovL3d3dy5taWNpdC5nby5jci9maXJtYWRpZ2l0YWwAMIIBiAYIYIE8AQEBAQcwggF6MIIBGAYIKwYBBQUHAgIwggEKHoIBBgBJAG0AcABsAGUAbQBlAG4AdABhACAAbABhACAAUABvAGwAaQB0AGkAYwBhACAAcABhAHIAYQAgAEMAZQByAHQAaQBmAGkAYwBhAGQAbwBzACAAZABlACAAQQBnAGUAbgB0AGUAIABFAGwAZQBjAHQAcgBvAG4AaQBjAG8AIABkAGUAIABQAGUAcgBzAG8AbgBhACAASgB1AHIAaQBkAGkAYwBhACAAcABlAHIAdABlAG4AZQBjAGkAZQBuAHQAZQAgAGEAIABsAGEAIABQAEsASQAgAE4AYQBjAGkAbwBuAGEAbAAgAGQAZQAgAEMAbwBzAHQAYQAgAFIAaQBjAGEAIAB2ADIwKgYIKwYBBQUHAgEWHmh0dHA6Ly93d3cuZmlybWFkaWdpdGFsLmdvLmNyADAwBggrBgEFBQcCARYkaHR0cDovL3d3dy5taWNpdC5nby5jci9maXJtYWRpZ2l0YWwAMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFODy/n3ERE5Q5DX9CImPToQZRDNAMIHSBgNVHR8EgcowgccwgcSggcGggb6GWmh0dHA6Ly93d3cuZmlybWFkaWdpdGFsLmdvLmNyL3JlcG9zaXRvcmlvL0NBJTIwUkFJWiUyME5BQ0lPTkFMJTIwLSUyMENPU1RBJTIwUklDQSUyMHYyLmNybIZgaHR0cDovL3d3dy5taWNpdC5nby5jci9maXJtYWRpZ2l0YWwvcmVwb3NpdG9yaW8vQ0ElMjBSQUlaJTIwTkFDSU9OQUwlMjAtJTIwQ09TVEElMjBSSUNBJTIwdjIuY3JsMIHmBggrBgEFBQcBAQSB2TCB1jBmBggrBgEFBQcwAoZaaHR0cDovL3d3dy5maXJtYWRpZ2l0YWwuZ28uY3IvcmVwb3NpdG9yaW8vQ0ElMjBSQUlaJTIwTkFDSU9OQUwlMjAtJTIwQ09TVEElMjBSSUNBJTIwdjIuY3J0MGwGCCsGAQUFBzAChmBodHRwOi8vd3d3Lm1pY2l0LmdvLmNyL2Zpcm1hZGlnaXRhbC9yZXBvc2l0b3Jpby9DQSUyMFJBSVolMjBOQUNJT05BTCUyMC0lMjBDT1NUQSUyMFJJQ0ElMjB2Mi5jcnQwDQYJKoZIhvcNAQENBQADggIBAL4VsG4xzoZGc4g8pc0WNckega6Vg5wq4LVMZjuEoPE3RwkVf2rt1kYWOushizP6PDTO2FGjOZtWDER8iVjhDCG4Q+NU5ppeVQcwnut1Lx9mGSUofKsmYQsH6vEz1HXx17Z/OVpqiGCJjElqgBx6TEdg1OZFAPGMJ65OOG050u7jA9oNgK+mv+Chj5WEOfdwk+2wr1dy+aRNjuVXzfOHebX6LMyGvHTxB+ETlNPpJt1YE2nphshtSiSyciCeKdr/7pplKMJiDGRPGKP4ZRY2Q+KSCmArgThESCQU89+C6+X8l/8RH/SnFDR+CRjLgavN3N+TYxD87FWcLVELAIO6nYyhnbuyhnZsr6/h11LeeL67GcshJOMp2SzslK1SQTNW3EgUbtWfwdqzObyuCMVyLTqUNLFcyfJZ30yFaNTPfXrVKrJU/PvgkNLMToj930ZYj0rUGQdNK6hNxyrk4JQkDjEgJyZVhNhnimkfIyXPiMz5IQ+Sp6EJbXTEcFcu4oIwRmocSNrcK8zuB4iH9Iw8asR7swQy7LVs/FpHjtt3ZChOdU3zMSkZQjj34611QJGPytlxAZUEyJ/9E8TiDp+4L1IJcNAeYKu32hPcsAaJweIwj14ICCZ1coGz+k0xHNUQzLQnfodCOL0h30y4EDR+yZhyXVyXHKr4VyZKMuU4zwdG
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
<ds:Object>
<xades:QualifyingProperties xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" Target="#id-ca8746e4c110c4a0dd6841ac562a5608">
<xades:SignedProperties Id="xades-id-ca8746e4c110c4a0dd6841ac562a5608">
<xades:SignedSignatureProperties>
<xades:SigningTime>2018-10-18T16:21:09Z</xades:SigningTime>
<xades:SigningCertificate>
<xades:Cert>
<xades:CertDigest>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>2b2BLsKOwj2gdAudBoVeA6EYJxg=</ds:DigestValue>
</xades:CertDigest>
<xades:IssuerSerial>
<ds:X509IssuerName>
CN=CA SINPE - PERSONA JURIDICA v2,OU=DIVISION SISTEMAS DE PAGO,O=BANCO CENTRAL DE COSTA RICA,C=CR,2.5.4.5=#131043504a2d342d3030302d303034303137
</ds:X509IssuerName>
<ds:X509SerialNumber>1605653654963390224028316123929917781715189888</ds:X509SerialNumber>
</xades:IssuerSerial>
</xades:Cert>
</xades:SigningCertificate>
</xades:SignedSignatureProperties>
<xades:SignedDataObjectProperties>
<xades:DataObjectFormat ObjectReference="#r-id-1">
<xades:MimeType>application/octet-stream</xades:MimeType>
</xades:DataObjectFormat>
</xades:SignedDataObjectProperties>
</xades:SignedProperties>
</xades:QualifyingProperties>
</ds:Object>
</ds:Signature>
</MensajeHacienda>
![error](https://user-images.githubusercontent.com/29420191/47170438-3ede1e80-d2c3-11e8-905f-eaeeaa6a100c.png)

**Pasos para reproducir**
Pasos para reproducir

**Sistema operativo:** *Cambiar por el S.O. (Windows, Linux, etc)*

**PHP versión:** *Cambiar por versión PHP.*

**MySQL versión:** *Cambiar por versión MySQL.*

**Comportamiento esperado**
Lo que debería pasar.

**Capturas de pantalla o registro de bitácora**
Si aplica, por favor adjuntar capturas o registros de logs con mensajes de error.

**Contexto adicional**
Cualquier otro contexto acá.

**Comment by crodriguez82** [comment]
![error](https://user-images.githubusercontent.com/29420191/47170476-587f6600-d2c3-11e8-9f0b-75cc3a4ea7ea.png)

**Comment by mamm26** [comment]
@crodriguez82: Hola, ¿has podido resolver el problema?, si es así, ¿por qué se presentaba?

**Comment by crodriguez82** [comment]
Hola @mamm26 en el json vi esto {"tipoIdentificacion":"False","numeroIdentificacion":"2562247"}, supongo que por este motivo fue el rechazo ya que no se armo bien el xml.

**Comment by crodriguez82** [comment]
tienes algún número o correo donde te pueda contactar?

**Comment by mamm26** [comment]
Perfecto, claro, te puedes comunicar por medio del Telegram, puedes ver los grupos desde aquí: https://crlibre.org/chats/

Una sugerencia, cuando vayas a subir algún tipo de código en el reporte (o los XML), puedes hacerlo desde este sitio: https://gist.github.com así se podrá ver correctamente compartiendonos el enlace.

**Comment by crodriguez82** [comment]
Gracias @mamm26
