### ISSUE TITLE
Monto en las notas de crédito

### ISSUE THREAD

**Issue by base64bits** [CRLibre/API_Hacienda#54]
Esto no es relacionado directamente al código del proyecto, pero si a su estructura.

Si uno emite una nota de crédito para anular una factura los montos de las lineas de la nota de credito incluyendo los montos totales tienen que ir en negativo en la nota de credito?

Nosotros hemos enviado todas las notas de credito con los montos en negativo y hacienda las acepta, pero un proveedor nos mandó una Nota de credito y los montos vienen en positivo así que no sabemos cual es la manera correcta.

Le agradezco su ayuda.

**Comment by mamm26** [comment]
Hola, la consulta no corresponde aquí, debido a que no es un problema de API. Puedes hacer la misma desde nuestro grupo de Telegram sobre la Facturación electrónica: https://t.me/CRLibreFE

**Comment by base64bits** [comment]
Gracias, voy en esas...
