### ISSUE TITLE
Mensaje en NC de parte de hacienda  extemporánea

### ISSUE THREAD

**Issue by crodriguez82** [CRLibre/API_Hacienda#57]
**Describa el problema** *(bug)*

Se crea NC se envía al API la solicitud este devuelve la fecha y hora correctamente en el comprobante pero en la firma la respuesta de hacienda sale con el día 21 de Octubre.

Valide a nivel de errors del API y veo lo siguiente

```log
[d] 18-10-21 12:10:10 @ Found function: send
[d] 18-10-21 12:10:10 @ JSON:{"clave":"50621101800310175301100100001030000000001136076435","fecha":"2018-10-20T18:51:56-06:00"
```

Comprobante xml

```xml
<NotaCreditoElectronica xmlns="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/notaCreditoElectronica" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/notaCreditoElectronica NotaCreditoElectronica_V4.2.xsd">
<Clave>50621101800310175301100100001030000000001136076435</Clave>
<NumeroConsecutivo>00100001030000000001</NumeroConsecutivo>
<FechaEmision>2018-10-20T18:51:56-06:00</FechaEmision>
```

Pero la firma lo genera con fecha del día siguiente

```xml
<ds:Object Id="XadesObjectId-43208d10-650c-4f42-af80-fc889962c9ac">
<xades:QualifyingProperties xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" Id="QualifyingProperties-012b8df6-b93e-4867-9901-83447ffce4bf" Target="#Signature-ddb543c7-ea0c-4b00-95b9-d4bfa2b4e411">
<xades:SignedProperties Id="SignedProperties-Signature-ddb543c7-ea0c-4b00-95b9-d4bfa2b4e411">
<xades:SignedSignatureProperties>
<xades:SigningTime>2018-10-21T00:52:09-06:00</xades:SigningTime>
<xades:SigningCertificate>
<xades:Cert>
<xades:CertDigest>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>BJcKpcjuVlpz7GYY7qK5fERn4nJprbrz7HDCuutk1Gc=</ds:DigestValue>
</xades:CertDigest>
<xades:IssuerSerial>
<ds:X509IssuerName>
```

Como puedo solucionar esto en la generación de la firma?

Este es un error del API?

**Pasos para reproducir**
Pasos para reproducir

**Sistema operativo:** *Cambiar por el S.O. (Windows, Linux, etc)*

**PHP versión:** *Cambiar por versión PHP.*

**MySQL versión:** *Cambiar por versión MySQL.*

**Comportamiento esperado**
Lo que debería pasar.

**Capturas de pantalla o registro de bitácora**
Si aplica, por favor adjuntar capturas o registros de logs con mensajes de error.

**Contexto adicional**
Cualquier otro contexto acá.

**Comment by mamm26** [comment]
Solucionado en d849b57b5a6e6a962771bdb05d0ce070b95ff835
