### ISSUE TITLE
Módulo checkXML no funciona

### ISSUE THREAD

**Issue by base64bits** [CRLibre/API_Hacienda#66]
**Describa el problema** *(bug)*
Módulo checkXML no funciona

**Pasos para reproducir**
Al enviar una llamada al API con el r checkxml el API devuelve null y no valida nada

**Versión API:** *
Version: 0d4d03e

**Sistema operativo:** 
Linux

**PHP versión:** *Cambiar por versión PHP.*
7.1

**Comportamiento esperado**
Devolver una serie de errores o un respuesta de que el XML está OK

**Contexto adicional**
Ya tengo todo reparado y listo para subirlo

**Comment by mamm26** [comment]
Hola, ¿podrías verificar la versión? Ya que actualmente no corresponde con alguna que tengamos nosotros.

**Comment by base64bits** [comment]
Acabo de descargar la versión más reciente del API desde acá y al revisar la versión me sigue dando 0d4d03e esto siguiendo las instrucciones aquí: https://github.com/CRLibre/API_Hacienda/blob/master/VERSION.md

**Comment by mamm26** [comment]
@base64bits: Es posible que estés trabajando en algún pull y es por ello que la versión no corresponde si haz realizado cambios en tu repositorio personal.

**Comment by base64bits** [comment]
ok revisando algunas cosas ahora me sale Version: edc5b78
