### ISSUE TITLE
Firma del documento mensaje receptor invalida con Hacienda

### ISSUE THREAD

**Issue by base64bits** [CRLibre/API_Hacienda#68]
**Describa el problema** *(bug)*
Firma del documento mensaje receptor invalida con Hacienda al firmar con el API

**Pasos para reproducir**
Pasos para reproducir
Firmar Mensaje Receptor y enviar a Hacienda

**Versión API:**
0d4d03e

**Sistema operativo:** *Cambiar por el S.O. (Windows, Linux, etc)*
Mac OS

**PHP versión:** *Cambiar por versión PHP.*
7.1

**Comportamiento esperado**
Hacienda debería de aceptar el documento firmado por el API

**Comment by mamm26** [comment]
Solucionado en 50af88e4f179c996ad14a4442094d89f67cda8ba
