### ISSUE TITLE
Opción para habilitar o deshabitar Error logging (grace_debug)

### ISSUE THREAD

**Issue by base64bits** [CRLibre/API_Hacienda#73]
**Describa el problema** *(bug)*
No existe opción para habilitar o deshabitar Error logging (grace_debug) 

**Pasos para reproducir**
Pasos para reproducir
Llamar el API desde cualquier módulo y al hacerlo si la función usa grace_debug el API hace un archivo en /errors con información necesaria para debugging, pero si esto no se necesita lo ideal seria poder activar o desactivar debugging desde el archivo settings.

**Versión API:** *Lea como obtener la versión del API 
Última versión

**Sistema operativo:** *Cambiar por el S.O. (Windows, Linux, etc)*
Mac OS/Linux

**PHP versión:** *Cambiar por versión PHP.*
7.2.1

**MySQL versión:** *Cambiar por versión MySQL.*
N/A

**Comment by mamm26** [comment]
dc18acbe537bfe78707bfa2b3e5639a525be9898
