### ISSUE TITLE
Código QR para el API

### ISSUE THREAD

**Issue by base64bits** [CRLibre/API_Hacienda#79]
**Describa el problema** *(bug)*
El API no tiene un módulo para generar el código QR, se que no es obligatorio o si lo va a ser, pero sería bueno estar preparados.

**Versión API:** *Lea como obtener la versión del API
Todas

**Comportamiento esperado**
Poder hacer un código QR con el API

**Contexto adicional**
Ya tengo el módulo listo, voy hacer un PR

**Comment by henrypandales** [comment]
Excelente, seria buenísimo hacer una version de esta api hacienda para Dian Colombia, teniendo en cienta la facturacion electronica. y un Gestor Documental 

alguien tienen un Sistema de Derivación de gestión documental?? gracias 
por favor escríbirme al whatsapp +57 314 775 4208
