### ISSUE TITLE
Respuesta Inesperada en Registro de Usuario

### ISSUE THREAD

**Issue by calberth19** [CRLibre/API_Hacienda#82]
**Describa el problema** *(bug)*
Estoy probando el inicio del la documentación. Al realizar la prueba de agregar un usuario me da un response: -301

**Pasos para reproducir**
Pasos para reproducir
1. pueden probarlo en https://sgmg.gridtechcr.com/api.php

**Versión API:** *Lea como obtener la versión del API https://github.com/CRLibre/API_Hacienda/blob/master/VERSION.md*

**Sistema operativo:** *Cambiar por el S.O. (Windows, Linux, etc)*
Linux

**PHP versión:** *Cambiar por versión PHP.*
PHP 7.2

**MySQL versión:** *Cambiar por versión MySQL.*
MariaDB 10
**Comportamiento esperado**
Deberia de agregar el user a la DB del API.

**Capturas de pantalla o registro de bitácora**
Si aplica, por favor adjuntar capturas, registros de logs con mensajes de error o XML (lo puedes subir a https://gist.github.com y nos compartes el enlace).

**Contexto adicional**
Cualquier otro contexto acá.
![Fallo](https://user-images.githubusercontent.com/47022404/54713613-a1f30c00-4b14-11e9-8e1b-765222c8aa85.PNG)

**Comment by calhoax19** [comment]
Veo que en contrib/users no existe el archivo register.php

**Comment by mamm26** [comment]
Hola, el problema es debido que necesitas iniciar sesión y obtener el `sessionKey` y añadirlo en los parámetros.

Inténtalo y me cuentas como te va.

**Comment by mamm26** [comment]
https://sgmg.gridtechcr.com/api.php?w=version&r=version

Al parecer el api no es manejado desde nuestro repositorio o ha sido manipulado, no tiene soporte.

**Comment by makeplerc** [comment]
tengo el mismo problema, alguna solucion, hace 2 dias que descargue el api

**Comment by makeplerc** [comment]
@calhoax19 yo solucione el problema importando el dump que esta en la carpeta recursos/sql

**Comment by cfao** [comment]
Tengo el mismo problema me da error 301..como lo solicionarom

**Comment by cfao** [comment]
Tengo el mismo problema me da error 301..como lo solicionaron

**Comment by gsusalvarado** [comment]
Hola buenas tengo el mismo problema pueden ayudarme  puedo loguearme y registrarme sin problemas siguiendo la documentación, pero cuando intento cerrar la session o subir el p12 obtengo -301

api.php?w=users&r=users_log_me_out      -301
@calhoax19  como es lo del dump que mencionas  yo en la base de datos cargue este script api_base.sql solamente

**Comment by fvega10** [comment]
Saludos colegas. 

**Problema**: Registro y Login funciona todo bien, Logout genera Error 403.

**¿Qué he hecho?:**
Recien descargué el repositorio, hice las configuraciones tal cual se indican en el paso a paso, implementé la solución en un ambiente de pruebas Linux , dominio con seguridad https.

Procedo a realizar las pruebas de registro de usuarios y login y ambas funcionan correctamente.

Realizo una prueba de logout y me genera error 403.

Valido que el sessionKey sea el mismo y efectivamente lo es, inclusive lo valido con el registro guardado en base de datos en la tabla sessions. Cabe decir que cualquier método que utilice y que requiere el sessionKey me genera el mismo error 403.

Lo hice tanto a nivel de Postman como también con un cliente Laravel.

El dump que cargué a la base de datos es el que está ubicado en la carpeta .../recursos/sql/api_base.sql (según recomendación de un comentario anterior), pero en inicio había cargado la que se indican en la documentación y aún así el problema era el mismo.

Me podría guiar de donde más podría revisar?
