### ISSUE TITLE
Actualizacion a version FE 4.3

### ISSUE THREAD

**Issue by schweini** [CRLibre/API_Hacienda#83]
Solo queria abrir el issue que hay que actualizar muchas partes a 4.3

Creo que lo mas importante es el firmador, por que que lleva v4.2 hardcoded - y no estoy seguro que eso hace falta? Alguien sabe por que el firmador modifica los encabezados?

**Comment by iMrLopez** [comment]
@schweini obtuviste respuesta en esto?

**Comment by schweini** [comment]
Lamentablemente, no.

**Comment by henry1592** [comment]
A partir de julio la 4.2 deja de funcionar 100% ? teniendo en cuenta que hacienda hasta hace unos días subió los xml en su versión 4.3 ?

**Comment by JeanCarlosChavarriaHughes** [comment]
sí

**Comment by droa6** [comment]
Saludos, por si aún es de utilidad para alguno, éstas modificaciones me sirvieron para usar el firmador con la versión 4.3

https://github.com/droa6/API_Hacienda/blob/master/api/contrib/signXML/Firmadohaciendacr.php

**Comment by mamm26** [comment]
@droa6: d4f327d49d99f180270db2c3660478c2a5fe023a

Gracias

**Comment by mamm26** [comment]
He comenzado la actualización a la v4.3 aquí #83

Les agradezco cualquier anotación o comentario para correcciones.

**Comment by JeanCarlosChavarriaHughes** [comment]
Hola. Los que tengan chance de poder revisar el siguiente PR: https://github.com/CRLibre/API_Hacienda/pull/88
Trata de resolver la actualización a versión FE 4.3 dividido en módulos.

**Comment by Lcarreno19** [comment]
tengo librería y firmador para la versión 4.3 disponible cualquier asesoría o información a mi correo luiscarreno1991@gmail.com
