### ISSUE TITLE
Problemas con la firma

### ISSUE THREAD

**Issue by gilmonge** [CRLibre/API_Hacienda#89]
**Describa el problema** *(bug)*
Error con la firma me genera el siguiente error por parte de hacienda "La firma del comprobante electrónico no es válida (El XML fue modificado luego de haber sido firmado)."
Yo ya utilizaba la api y me iba de maravilla actualice los archivos para la nueva version y no me recibe ningún comprobante

**Pasos para reproducir**
Se genera al realizar la firma de documentos electrónicos

**Versión API:** *"Version: d4f327d"*

**Sistema operativo:** *Linux (ubuntu server)*

**Nota:**
*No se si es mejor que solo remplace los archivos modificados o por completo*

**Comment by JeanCarlosChavarriaHughes** [comment]
Hola @gilmonge 
Puedes tratar con este #88 , firmarxml en lugar de signxml. Es la implementación del nuevo firmador de enzojimenez, dentro de la API_Hacienda. 
Entiendo que el firmador legacy, signxml no está actualizado para funcionar en 4.2 y 4.3 simultáneamente.

**Comment by enzojimenez** [comment]
En efecto, el firmador legacy no es compatible con 4.3 del todo.

**Comment by FredMorganCTO** [comment]
Ahora tengo el mismo problema exacto, y mi código solía funcionar bien. ¿Sabemos si este cambio soluciona el problema? He actualizado al último código, pero no veo firmarxml en él.

Gracias por tu ayuda.

**Comment by gilmonge** [comment]
> 
> En efecto, el firmador legacy no es compatible con 4.3 del todo.

En ese caso que se procede ? Ignorar el firmador del api o esperar a que lo solucionen?

**Comment by JeanCarlosChavarriaHughes** [comment]
Porque no trata de usar el código de este Pull Request, y usar el firmador _firmarxml_, a mi me funciona

**Comment by enzojimenez** [comment]
@JeanCarlosChavarriaHughes  man, es PR ¿sigue abierto? Pensé ya le habian hecho merge

**Comment by gilmonge** [comment]
> Porque no trata de usar el código de este Pull Request, y usar el firmador _firmarxml_, a mi me funciona

@JeanCarlosChavarriaHughes yo ya poseo los últimos cambios que se encuentran en el repositorio sin embargo poseo diferentes errores:

`
<Clave>5060909190031012-----00100001040000000003195418074</Clave>
<NombreEmisor>DESCONOCIDO</NombreEmisor>
<TipoIdentificacionEmisor>02</TipoIdentificacionEmisor>
<NumeroCedulaEmisor>0031012-----</NumeroCedulaEmisor>
<Mensaje>3</Mensaje>
<DetalleMensaje>Este comprobante fue aceptado en el ambiente de pruebas, por lo cual no tiene validez para fines tributarios
La firma del comprobante electrónico no es válida (El XML fue modificado luego de haber sido firmado).
</DetalleMensaje>
<TotalFactura>0</TotalFactura>
`

No se se si me podrían dar algunas pistas de los errores que me da hacienda
Se los agradecería de antemano

**Comment by jairo0920** [comment]
En mi caso @gilmonge, me da el mismo problema **"La firma del comprobante electrónico no es válida (El XML fue modificado luego de haber sido firmado)"** y compare la branches master con la branches v4.3 y encontre diferencias en el modulo de genXML, no se si sera ese el caso, veo que en el archivo xmlGenerator.php aún tiene los $headerDoc en la version v4.2

**Comment by gilmonge** [comment]
En mi caso yo actualice todo el genxml en la sección de tiquete electrónico sigo en pruebas pero me dejó de aparecer ese error cuando actualice los encabezados hacia los de la 4.3 deberías de intentarlo

**Comment by jairo0920** [comment]
Ya aparece como aceptados los TE.? Me puedes enviar los archivos al correo jairo@cruz.cr

**Comment by gilmonge** [comment]
Estoy trabajando todavía en la api porque hay un error que me sale cuando lo solucione se lo puedo enviar

**Comment by gilmonge** [comment]
Buenas @jairo0920 , @JeanCarlosChavarriaHughes 
El problema que me tope no era con el firmador era con el generador de xml he realizado unos ajustes en el código aporto una carpeta en drive donde pueden accesar al código, sigo con cambios y pensare cargarlos ahí para que al final ver si se pueden incluir en el api
[Cambios en genxml.php (TE - drive)](https://drive.google.com/drive/folders/1vPovqFGAVpRfjx4HC73qOezvN1rp-pjq)

**Comment by JeanCarlosChavarriaHughes** [comment]
> @JeanCarlosChavarriaHughes man, es PR ¿sigue abierto? Pensé ya le habian hecho merge

Correcto, Sigue Abierto. Significa que el código del master está usando la versión vieja que no se ha actualizado.

@gilmonge  @jairo0920  
Este código está actualizado: https://github.com/JeanCarlosChavarriaHughes/API_Hacienda.git
El master que uds están usando no está actualizado, por eso es esperable que falle.

**Comment by FredMorganCTO** [comment]
Disculpe, puedo leer bien el español, pero estoy un poco confundido. ¿Qué debo hacer exactamente para solucionar este problema? Actualmente estoy usando el último código de GIT. Sigo teniendo el mismo problema.

Gracias por su tiempo y trabajo duro en este tema.

**Comment by FredMorganCTO** [comment]
He resuelto el problema con la firma, ahora solo tengo que actualizar cosas como CodigoTarifa, etc.

Buscando tablas para esto.

**Comment by gilmonge** [comment]
> 
> 
> He resuelto el problema con la firma, ahora solo tengo que actualizar cosas como CodigoTarifa, etc.
> 
> Buscando tablas para esto.

Casi la mayoria de los codigos se encuentran en los detalles de los xml de hacienda, **puedes ver los XML oficiales [aquí](https://www.hacienda.go.cr/ATV/ComprobanteElectronico/frmAnexosyEstructuras.aspx#)**

**Comment by ecarrillo01** [comment]
Veo que ahora en los settings .php las configuracions las llama desde un .env, podria pasar un ejemplo del .env, es que yo creo un archivo .env en el proyecto y pongo los valores pero no me funciona

**Comment by jairo0920** [comment]
> > @JeanCarlosChavarriaHughes man, es PR ¿sigue abierto? Pensé ya le habian hecho merge
> 
> Correcto, Sigue Abierto. Significa que el código del master está usando la versión vieja que no se ha actualizado.
> 
> @gilmonge @jairo0920
> Este código está actualizado: https://github.com/JeanCarlosChavarriaHughes/API_Hacienda.git
> El master que uds están usando no está actualizado, por eso es esperable que falle.

Hola, todo bien.! Vieras que estaba probando tu codigo pero en el momento que realizo la firma del XML con el modulo "firmarXML", no me devuelve nada "Operation timed out after 30001 milliseconds with 0 bytes received", lo realizo con el modulo "signXML" pero me rechaza el TE, me indica este error: "Error al comunicarse con el Signum One"

**Comment by ecarrillo01** [comment]
@JeanCarlosChavarriaHughes  cuando actualizo al fix suyo de 4.3 ahora es el metodo de generar tiquete que no me funciona

**Comment by JeanCarlosChavarriaHughes** [comment]
@ecarrillo01 
cuál error le tira? hay varios campos nuevos que hay que mandar en el request

**Comment by ecarrillo01** [comment]
> @ecarrillo01
El request es el del drive 

{
    "w": "genXML",
    "r": "gen_xml_te",

    "clave": "50610091900310100000000100001040000000001184393380",
    "consecutivo": "00100001040000000001",
    "CodigoActividad": "722003",
    "fecha_emision": "2019-09-10T09:28:22-06:00",

    "emisor_nombre": "Empresa",
    "emisor_tipo_indetif": "02",
    "emisor_num_identif": "3101000000",
    "nombre_comercial": "Empresa",
    "emisor_provincia": "1",
    "emisor_canton": "18",
    "emisor_distrito": "01",
    "emisor_barrio": "07",
    "emisor_otras_senas": "Curridabat",
    "emisor_cod_pais_tel": "506",
    "emisor_tel": "22710000",
    "emisor_email": "info@empresa.com",

    "receptor_nombre": "Gilberth Monge",
    "receptor_tipo_identif": "01",
    "receptor_num_identif": "303330333",
    "receptor_provincia": "3",
    "receptor_canton": "01",
    "receptor_distrito": "10",
    "receptor_barrio": "01",
    "receptor_otras_senas": "Cartago",
    "receptor_cod_pais_tel": "506",
    "receptor_tel": "88888888",
    "receptor_cod_pais_fax": "506",
    "receptor_fax": "",
    "receptor_email": "gilmonge@mail.com",

    "condicion_venta": "01",
    "plazo_credito": "00",
    "medio_pago": "04",
    "cod_moneda": "CRC",
    "tipo_cambio": "1.00000",

    "total_serv_gravados": "11025.23000",
    "total_serv_exentos": "0.00000",
    "total_serv_exonerado": "0.00000",
    "total_merc_gravada": "0.00000",
    "total_merc_exenta": "0.00000",
    "total_merc_exonerada": "0.00000",
    "total_gravados": "11025.23000",
    "total_exentos": "0.00000",
    "total_ventas": "11025.23000",
    "total_exonerado": "0.00000",
    "total_descuentos": "907.57000",
    "total_ventas_neta": "10117.66000",
    "total_impuestos": "1082.35000",
    "total_comprobante": "11200.01000",

    "otros": "ND",
    "otrosType": "Tiquete Electronico",
    
    "detalles":"{\"1\":{\"codigo\":\"2\",\"codigocomercial\":{\"tipo\":\"01\",\"codigo\":\"2\"},\"cantidad\":\"1.000\",\"unidadMedida\":\"Sp\",\"unidadmedidacomercial\":\"Otros\",\"detalle\":\"Nivel\",\"precioUnitario\":\"1525.00000\",\"montoTotal\":\"1525.00000\",\"subtotal\":\"1067.50000\",\"montoTotalLinea\":\"1088.85000\",\"ImpuestoNeto\":\"21.35000\",\"montoDescuento\":\"457.50000\",\"naturalezaDescuento\":\"Descuento\",\"impuesto\":{\"1\":{\"codigo\":\"01\",\"CodigoTarifa\":\"03\",\"tarifa\":\"2.00000\",\"monto\":\"21.35000\"}}},\"2\":{\"codigo\":\"7\",\"codigocomercial\":{\"tipo\":\"01\",\"codigo\":\"7\"},\"cantidad\":\"1.000\",\"unidadMedida\":\"Sp\",\"unidadmedidacomercial\":\"Otros\",\"detalle\":\"Inglés \",\"precioUnitario\":\"1500.23000\",\"montoTotal\":\"1500.23000\",\"subtotal\":\"1050.16000\",\"montoTotalLinea\":\"1071.16000\",\"ImpuestoNeto\":\"21.00000\",\"montoDescuento\":\"450.07000\",\"naturalezaDescuento\":\"Descuento\",\"impuesto\":{\"1\":{\"codigo\":\"01\",\"CodigoTarifa\":\"03\",\"tarifa\":\"2.00000\",\"monto\":\"21.00000\"}}},\"3\":{\"tipo\":\"01\",\"codigo\":\"1\",\"codigocomercial\":{\"tipo\":\"01\",\"codigo\":\"1\"},\"cantidad\":\"1.000\",\"unidadMedida\":\"Sp\",\"unidadmedidacomercial\":\"Otros\",\"detalle\":\"Gestión de matricula\",\"precioUnitario\":\"3000.00000\",\"montoTotal\":\"3000.00000\",\"subtotal\":\"3000.00000\",\"montoTotalLinea\":\"3390.00000\",\"ImpuestoNeto\":\"390.00000\",\"impuesto\":{\"1\":{\"codigo\":\"01\",\"CodigoTarifa\":\"08\",\"tarifa\":\"13.00000\",\"monto\":\"390.00000\"}}},\"4\":{\"tipo\":\"01\",\"codigo\":\"2\",\"codigocomercial\":{\"tipo\":\"01\",\"codigo\":\"2\"},\"cantidad\":\"1.000\",\"unidadMedida\":\"Sp\",\"unidadmedidacomercial\":\"Otros\",\"detalle\":\"Material de aprendizaje\",\"precioUnitario\":\"5000.00000\",\"montoTotal\":\"5000.00000\",\"subtotal\":\"5000.00000\",\"montoTotalLinea\":\"5650.00000\",\"ImpuestoNeto\":\"650.00000\",\"impuesto\":{\"1\":{\"codigo\":\"01\",\"CodigoTarifa\":\"08\",\"tarifa\":\"13.00000\",\"monto\":\"650.00000\"}}}}"
}


Lo que me esta respondiendo es esto 

{
    "resp": -1
}<br />
<b>Warning</b>:  implode(): Invalid arguments passed in <b>/var/www/html/API_Hacienda/api/core/grace.php</b> on line <b>85</b><br />
<br />
<b>Warning</b>:  fopen(../api/logs/wirez_19_09_17_03.txt): failed to open stream: No such file or directory in <b>/var/www/html/API_Hacienda/api/core/grace.php</b> on line <b>88</b><br />

**Comment by JeanCarlosChavarriaHughes** [comment]
Sí, ese drive no está actualizado. Revise el genXml.php
Por ejemplo a simple vista
emisor_tipo_indetif
Ahora es 
emisor_tipo_identif. 
Medio_pago hacienda lo cambió a una lista entonces es medios_pago que recibe un json

**Comment by JeanCarlosChavarriaHughes** [comment]
Este es un ejemplo de XML generado y firmado con esta versión. Según https://apis.gometa.org/validar/ la firma está correcta y el XML no tiene problemas.

https://gist.github.com/JeanCarlosChavarriaHughes/80c98f0c03aa5092723e711e24b975b1#file-50617091900070211023500100001010000000063184619703-xml

**Comment by ecarrillo01** [comment]
Muchas gracias, estoy comparando y ya encontré un error en mi xml

Eduardo Carrillo Salvatierra

**Comment by ERugama** [comment]
hola @jairo0920  a mi tambien me dio un problema "Error al comunicarse con el Signum One" quería saber como pudiste resolver ese detalle y gracias por el aporte.

**Comment by ERugama** [comment]
@JeanCarlosChavarriaHughes muy buenas noches mi estimado, bendiciones. queria saber si me pueden ayudar con respecto al problema de "Error al comunicarse con el Signum One" y muchas gracias por el aporte.

**Comment by JeanCarlosChavarriaHughes** [comment]
@ERugama  no entiendo a que error se refiere? Creo que no hay conexión entre el API_Hacienda y el Signum One

**Comment by ERugama** [comment]
@JeanCarlosChavarriaHughes  el MensajeHacienda me dice:  <DetalleMensaje>Este comprobante fue aceptado en el ambiente de pruebas, por lo cual no tiene validez para fines tributarios

Error al comunicarse con el Signum One</DetalleMensaje>

**Comment by JeanCarlosChavarriaHughes** [comment]
Creo que es normal si está en pruebas. 
Lo del Signum One yo no lo estoy usando :/

**Comment by agcgithub** [comment]
[ La firma del comprobante electrónico no es válida (El XML fue modificado luego de haber sido firmado). ] 

Tengo este error al enviar el documento en 4.4
Solamente modifiqué la URL del PDF

 "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/Resoluci%C3%B3n_General_sobre_disposiciones_t%C3%A9cnicas_comprobantes_electr%C3%B3nicos_para_efectos_tributarios.pdf"

 y el respectivo valor

DWxin1xWOeI8OuWQXazh4VjLWAaCLAA954em7DMh0h8=

Es el único cambio que hice con relación a la veersión 4.3

Alguien me puede dar una luz al respecto?

**Comment by agcgithub** [comment]
> He resuelto el problema con la firma, ahora solo tengo que actualizar cosas como CodigoTarifa, etc.
> 
> Buscando tablas para esto.

Me podrías ayudar con la firma, tengo este error

[ La firma del comprobante electrónico no es válida (El XML fue modificado luego de haber sido firmado). ] 

Únicamente cambié el PDF

https://cdn.comprobanteselectronicos.go.cr/xml-schemas/Resoluci%C3%B3n_General_sobre_disposiciones_t%C3%A9cnicas_comprobantes_electr%C3%B3nicos_para_efectos_tributarios.pdf

 y el valor del digest, 

DWxin1xWOeI8OuWQXazh4VjLWAaCLAA954em7DMh0h8=

lo demás lo tengo igual que la versión 3.3.
