### ISSUE TITLE
Crear Documentacion

### ISSUE THREAD

**Issue by walner1borbon** [CRLibre/API_Hacienda#9]
Buenos dias 
Ocupamos crear una documentacion para el API.
Agradezco si alguien puede colaborar, favor me contactan por el chat de CRLibre en whatsapp o por este mismo medio.
Saludos

**Comment by jaullo** [comment]
Buenos días,
Soy desarrollador con experiencia en muchas tecnologías y actualmente me encuentro revisando el API para tratar de entender su funcionamiento y llevarlo a una interfaz para consumirlo. Si alguno está dispuesto ha tomarse el tiempo para explicarme un poco mas el funcionamiento puedo ir generando la documentación. Ya que si lo hago sin la colaboración de los que han desarrollado puede que en algunos casos sea errónea o bien me tome mas tiempo
