### ISSUE TITLE
Rechazo de tiquete

### ISSUE THREAD

**Issue by ecarrillo01** [CRLibre/API_Hacienda#90]
Al enviar un tiquete hacienda lo rechaza con este mensaje de error

El comprobante electrónico tiene los siguientes errores: \n\n[\ncodigo, mensaje, fila, columna\n-1, \"cvc-datatype-valid.1.2.1: '' is not a valid value for 'decimal'.\", 90, 26\n\n]

**Comment by JeanCarlosChavarriaHughes** [comment]
Puedes copiar el output del servidor. Ejemplo, si está usando apache, copiar el output de /var/log/apache2/error.log . Con eso se puede debuguear mejor el error. @ecarrillo01

**Comment by FredMorganCTO** [comment]
> 
> 
> Al enviar un tiquete hacienda lo rechaza con este mensaje de error
> 
> El comprobante electrónico tiene los siguientes errores: \n\n[\ncodigo, mensaje, fila, columna\n-1, "cvc-datatype-valid.1.2.1: '' is not a valid value for 'decimal'.", 90, 26\n\n]

Puedo ayudar con esto: esto significa que en el XML que envió, en la línea 90 hay un error, generalmente porque no lo completó. Puede averiguar dónde está la línea 90 abriendo el XML firmado en algo como notepad ++. Hay muchos campos nuevos que se requieren ahora, que antes no lo eran, y no hay valores predeterminados para ellos. ¡Sé feliz, ya casi estás allí! Solo tiene que dar valores para los nuevos campos obligatorios.

Tenía estos campos que tenía que resolver:

        $list['total_exonerado']=0;
        $list['total_serv_exonerado']=0;
        $list['total_merc_exonerada']=0;

**Comment by ecarrillo01** [comment]
> Puedes copiar el output del servidor. Ejemplo, si está usando apache, copiar el output de /var/log/apache2/error.log . Con eso se puede debuguear mejor el error. @ecarrillo01

Ya pude enviar el tiquete y hacienda responde aceptado, pero cuando consulto lo consulto por numero de consecutivo en el atv no sale nada

**Comment by LionSolutions** [comment]
> > Puedes copiar el output del servidor. Ejemplo, si está usando apache, copiar el output de /var/log/apache2/error.log . Con eso se puede debuguear mejor el error. @ecarrillo01
> 
> Ya pude enviar el tiquete y hacienda responde aceptado, pero cuando consulto lo consulto por numero de consecutivo en el atv no sale nada

la consulta se hace por numero de clave.

**Comment by JeanCarlosChavarriaHughes** [comment]
Parece que ya se puede cerrar este Issue.
@eliastorres
