### ISSUE TITLE
New XML types : FEE, FEC

### ISSUE THREAD

**Issue by FredMorganCTO** [CRLibre/API_Hacienda#93]
Pardon my English - I can read Spanish just fine, but it is a bit of a challenge to write Spanish.

There are two new submissions I need from 4.3:

    Factura electrónica de exportación: la cual debe ser utilizada tanto para la exportación de mercancías como de servicios.
    Factura electrónica de compra: es utilizada para la compra de bienes o servicios a contribuyentes excluidos del uso de comprobantes electrónicos.

Are they implemented yet? And if not - I don't mind doing it.  I am going to need both very soon - I probably should have already done them.

Thank you.

**Comment by JeanCarlosChavarriaHughes** [comment]
@FredMorganCTO  AKAIK nobody has worked on it yet.

++cc @mamm26  @eliastorres

**Comment by FredMorganCTO** [comment]
Isn't Factura electrónica de compra a requirement for this year?

**Comment by JeanCarlosChavarriaHughes** [comment]
@FredMorganCTO 
were you able to go into this development? 
[
> 

](https://github.com/CRLibre/API_Hacienda/issues/93#issue-513451922)
