### ISSUE TITLE
Problemas con la Libreria

### ISSUE THREAD

**Issue by fariasc** [CRLibre/API_Hacienda#95]
Problema : Al llamar a la librería (http://www.kafcorp.net/api.php?w=ejemplor=hola), en json me regresa el siguiente mensaje: {"resp":"Module not found"}<br />
<b>Warning</b>:  implode(): Invalid arguments passed in <b>/opt/lampp/api/core/grace.php</b> on line <b>85</b><br />

La libreria esta corriendo en un servidor Linux RedHat 7.2, sobre lampp, separe las carpetas según lo indicado en la documentación, los archivos api.php y  settings.php estan en la rais de htdocs, en el siguiente PATH : opt/lampp/htdocs/, la carpeta api esta en : opt/lampp/ el archivo de configuracion settings.php en la linea de core and modules quedo de la siguiente manera : $config['modules']['coreInstall'] = "../api/"; 

Cual sería la solución ?

**Comment by PeterPedro** [comment]
Le recomiendo este fork https://github.com/walner1borbon/API_Hacienda
