### ISSUE TITLE
Mensaje de error "La informacion json enviada contiene errores."

### ISSUE THREAD

**Issue by MIKECOL123** [CRLibre/API_Hacienda#97]
Hola a todos, gracias por la API y feliz año en primer lugar, ahora bien
Estoy realizando la instalación del API y una vez que logré corregir el error de "la carpeta api no ha sido encontrada" ahora me encuentro con este mensaje "La informacion json enviada contiene errores." 
Alguno sabe del porque presenta este error, ya obtuve la llave criptografica desde "http://api-demo.crlibre.org/api.php?w=crypto&r=makeKey" y la configure en el archivo settings

`

$config['db']['name'] = 'databasename';

$config['db']['pwd'] = 'password';

$config['db']['user'] = 'databaseuser';

$config['db']['host'] = 'databaseHost';

#
# Crypto Keys
#

$config['crypto']['key'] = 'Llave obtenida de http://api-demo.crlibre.org/api.php?w=crypto&r=makeKey '

# print alerts
# false or true
#
$config['boot']['alert'] = 'true';
##
##
$config['debug']['print_all']    = true;
$config['debug']['print_absurd'] = true;
$config['debug']['print_debug']  = true;
$config['debug']['print_error']  = true;

#
# Emails
#

# Options: "mail" or "smtp".
$config['mail']['type']         = "mail";
# Used in "mail" or "smtp"
$config['mail']['address']      = 'noreplay@gmail.com';       // for example: info@crlibre.org
$config['mail']['noreply']      = "";       // Optional - for example: no-reply@crlibre.org
# If "smtp" option is actived.
$config['mail']['host']         = "";
$config['mail']['username']     = "";
$config['mail']['password']     = "";
$config['mail']['secure']       = "tls";    // Use tls or ssl
$config['mail']['port']         = 587;

#
# Core and Modules 
#

# The core installation: This is probably the only one you need to touch
# IMPORTANTE: La ruta debe finalizar en "/".
$config['modules']['coreInstall'] = "../api/";

$config['core']['siteName'] = 'MySite';
$config['core']['host'] = "mySite.com";
$config['core']['compannyIMG'] = 'https://testhaciendaapi.com/';

$config['users']['sessionLifetime'] = 1000;

/*******************************************************************************
 * You should not need to touch anything beyond this point
 */
`
**Pasos para reproducir**
1. url de la api, 
Ejemplo: https://testhaciendaapi.com/api.php

**Versión API:** *
Version: b169480
Por cierto, solo me aparece cuando hago el llamado en Local, desde el server no funciona

**Sistema operativo:** 
En local uso windows y en el server linux pero en ambos me muestran el mismo error de
"La informacion json enviada contiene errores."

**PHP versión:**
PHP Version 7.3.9

**MySQL versión:** *
10.4.6

P.S. alguno sabe porque cuando se ejecuta "http://api-demo.crlibre.org/api.php" la respuesta es "{"resp":"Module not found"}" saben si dejo de funcionar por alguna razón o simplemente lo quitaron?

Saludos!

**Comment by eddy-dot** [comment]
Tengo el mismo problema

**Comment by caaddri** [comment]
Buenas tardes colegas, alguno lo logró resolver, tengo el mismo problema. Saludos

**Comment by andreselmomoy** [comment]
Me daba el mismo problema lo solucione quitando el getenv de :
$config['db']['name'] = 'db';
# Database password
$config['db']['pwd'] = 'ps';
# Database user name
$config['db']['user'] = 'ff';
# Database host
$config['db']['host'] = 'localhost';

$config['crypto']['key'] =  "crypto";
$config['users']['sessionLifetime'] = 1000;
